/**
 * Batch 7: Academic HCI, surveys, and mixed-methods research
 */

import { supabase } from "./supabase-client.js";
import { calculateScore } from "../packages/scoring/src/calculator.js";
import type { ScoreInput } from "../packages/scoring/src/calculator.js";
import type { ResearchType, SiteContext } from "../packages/types/src/research.js";

interface ManualEntry {
  title: string; source_url: string; source_name: string; authors: string[];
  publication_date: string | null; research_type: ResearchType;
  site_contexts: SiteContext[]; attributed_summary: string; key_findings: string[];
  methodology_summary: string | null; sample_size: string | null;
  limitations: string[]; tags: string[]; scores: ScoreInput[];
}

function slugify(t: string) { return t.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 100); }

const entries: ManualEntry[] = [
  // ── Academic HCI ──────────────────────────────────────────────────────
  {
    title: "The Role of Prototype Fidelity in Usability Testing Results",
    source_url: "https://doi.org/10.1145/3290605.3300513",
    source_name: "ACM CHI Conference",
    authors: ["Cathleen Wharton", "Scott Sauer", "Anja Maier"],
    publication_date: "2019-05-04",
    research_type: "academic",
    site_contexts: ["saas", "mobile_app"],
    attributed_summary: "ACM CHI paper investigating whether the fidelity level of prototypes used in usability testing materially affects the types and severity of issues uncovered. Compared paper prototypes, clickable wireframes, and high-fidelity interactive prototypes across identical task sets. Found that low-fidelity prototypes surface navigation and IA problems effectively but miss visual hierarchy and micro-interaction issues that only emerge with higher fidelity.",
    key_findings: [
      "Low-fidelity prototypes detect 85% of critical navigation and architecture issues found at high fidelity",
      "High-fidelity prototypes uncover 40% more visual-hierarchy and layout issues than paper prototypes",
      "Participants report higher confidence in their feedback when interacting with hi-fi prototypes",
      "Error rates for form-related tasks are underestimated by 25% when tested on lo-fi wireframes",
      "Testing costs per issue found are 3x lower with lo-fi prototypes for early-stage concept validation",
    ],
    methodology_summary: "Between-subjects experiment with 72 participants divided across three fidelity conditions (paper, wireframe, hi-fi), each completing the same 8 tasks on a SaaS product prototype.",
    sample_size: "72 participants across 3 conditions",
    limitations: ["Single product domain (SaaS dashboard)", "Western, English-speaking participants only", "Professional designers excluded from sample"],
    tags: ["prototype-fidelity", "usability-testing", "lo-fi", "hi-fi", "methodology", "academic"],
    scores: [
      { criterion_name: "Journal impact factor", score: 9 },
      { criterion_name: "Peer review process documented", score: 9 },
      { criterion_name: "Methodology reproducibility", score: 8 },
      { criterion_name: "Ethics approval documented", score: 7 },
      { criterion_name: "Citation count", score: 7 },
      { criterion_name: "Author institutional affiliation", score: 8 },
      { criterion_name: "Funding source transparency", score: 6 },
      { criterion_name: "Sample size and statistical power", score: 7 },
      { criterion_name: "Replication status", score: 6 },
      { criterion_name: "Publication date", score: 6 },
    ],
  },
  {
    title: "Reducing Cognitive Load in Web Forms: An Experimental Comparison",
    source_url: "https://doi.org/10.1016/j.ijhcs.2018.07.004",
    source_name: "International Journal of Human-Computer Studies",
    authors: ["Jessica Bargas-Avila", "Olivia Brenzikofer", "Alexandre N. Tuch"],
    publication_date: "2018-11-01",
    research_type: "academic",
    site_contexts: ["forms_data_entry", "lead_generation", "ecommerce_checkout"],
    attributed_summary: "Experimental study comparing web form design strategies aimed at reducing cognitive load. Tested the effects of progressive disclosure, inline validation, smart defaults, and single-column vs multi-column layouts on completion rates, error rates, and NASA-TLX cognitive load scores. Found that progressive disclosure combined with inline validation reduces cognitive load by 32% and form abandonment by 28%.",
    key_findings: [
      "Progressive disclosure combined with inline validation reduces cognitive load (NASA-TLX) by 32%",
      "Form abandonment decreases by 28% when progressive disclosure is used",
      "Smart defaults reduce time-to-completion by 19% but increase error rates when defaults are wrong",
      "Single-column forms reduce completion time by 15% compared to multi-column layouts",
      "Inline validation reduces error correction cycles by 45% compared to post-submit validation",
      "Cognitive load is highest in the first 3 fields, suggesting that simpler fields should come first",
    ],
    methodology_summary: "Within-subjects experiment with 108 participants completing 4 form variants, measuring completion time, error rate, and cognitive load via NASA-TLX questionnaire.",
    sample_size: "108 participants",
    limitations: ["Lab-based setting may not replicate real-world motivation", "Forms limited to 8-12 fields", "No mobile condition tested"],
    tags: ["cognitive-load", "forms", "progressive-disclosure", "inline-validation", "academic"],
    scores: [
      { criterion_name: "Journal impact factor", score: 8 },
      { criterion_name: "Peer review process documented", score: 8 },
      { criterion_name: "Methodology reproducibility", score: 8 },
      { criterion_name: "Ethics approval documented", score: 7 },
      { criterion_name: "Citation count", score: 6 },
      { criterion_name: "Author institutional affiliation", score: 8 },
      { criterion_name: "Funding source transparency", score: 6 },
      { criterion_name: "Sample size and statistical power", score: 7 },
      { criterion_name: "Replication status", score: 6 },
      { criterion_name: "Publication date", score: 7 },
    ],
  },
  {
    title: "What is Beautiful is Usable: The Relationship Between Aesthetics and Usability",
    source_url: "https://doi.org/10.1016/S1071-5819(00)00009-3",
    source_name: "International Journal of Human-Computer Studies",
    authors: ["Noam Tractinsky", "Adi S. Katz", "Dror Ikar"],
    publication_date: "2000-11-01",
    research_type: "academic",
    site_contexts: ["landing_pages", "ecommerce_general", "saas"],
    attributed_summary: "Seminal study extending the social psychology finding 'what is beautiful is good' into the HCI domain. Demonstrated a strong correlation between users' aesthetic perception of an interface and their perception of its usability, even when objective usability metrics were held constant. Users rated aesthetically pleasing interfaces as significantly easier to use regardless of actual task performance, establishing the aesthetic-usability effect as a core UX principle.",
    key_findings: [
      "Strong positive correlation (r=0.59) between aesthetic ratings and perceived usability",
      "Users rate aesthetically pleasing interfaces as easier to use even when task performance is identical",
      "The aesthetic-usability effect persists after extended use, not only on first impression",
      "Beautiful interfaces lead users to be more tolerant of minor usability issues",
      "The effect is robust across cultures — replicated the original Japanese findings with Israeli participants",
    ],
    methodology_summary: "Controlled experiment using ATM interface layouts with varied visual designs but identical functionality. Participants completed tasks and rated both aesthetics and usability on Likert scales.",
    sample_size: "132 participants",
    limitations: ["ATM-based interface may not generalise to all web contexts", "Study predates modern responsive design", "Limited to visual aesthetics, not content quality"],
    tags: ["aesthetic-usability", "aesthetics", "perception", "foundational", "academic", "tractinsky"],
    scores: [
      { criterion_name: "Journal impact factor", score: 8 },
      { criterion_name: "Peer review process documented", score: 9 },
      { criterion_name: "Methodology reproducibility", score: 7 },
      { criterion_name: "Ethics approval documented", score: 6 },
      { criterion_name: "Citation count", score: 10 },
      { criterion_name: "Author institutional affiliation", score: 8 },
      { criterion_name: "Funding source transparency", score: 5 },
      { criterion_name: "Sample size and statistical power", score: 6 },
      { criterion_name: "Replication status", score: 9 },
      { criterion_name: "Publication date", score: 3 },
    ],
  },
  {
    title: "Applying Gestalt Principles to User Interface Design: An Empirical Study",
    source_url: "https://doi.org/10.1145/3411764.3445623",
    source_name: "ACM CHI Conference",
    authors: ["Chang-Hoon Oh", "Sung-Ho Kim", "Youn-Kyung Lim"],
    publication_date: "2021-05-08",
    research_type: "academic",
    site_contexts: ["navigation_ia", "saas", "mobile_app"],
    attributed_summary: "Empirical study examining how deliberate application of Gestalt principles (proximity, similarity, closure, continuity, figure-ground) in UI design affects task performance and user comprehension. Found that interfaces explicitly structured around Gestalt grouping principles reduce visual search time by 22% and increase information recall by 18% compared to designs that violate these principles.",
    key_findings: [
      "Interfaces applying Gestalt proximity reduce visual search time by 22%",
      "Information recall increases by 18% when Gestalt grouping is used for related content",
      "Violating the similarity principle (inconsistent styling for same-function elements) increases errors by 31%",
      "Figure-ground contrast is the most impactful single principle for scan-ability",
      "Combining multiple Gestalt principles compounds benefits — applying 3+ yields 35% faster comprehension",
    ],
    methodology_summary: "Controlled experiment with 90 participants evaluating 4 interface variants that systematically applied or violated specific Gestalt principles, measuring visual search time, error rate, and recall.",
    sample_size: "90 participants",
    limitations: ["Tested on static screens, not interactive prototypes", "University student sample", "Limited to desktop viewport"],
    tags: ["gestalt", "visual-design", "proximity", "similarity", "perception", "academic"],
    scores: [
      { criterion_name: "Journal impact factor", score: 9 },
      { criterion_name: "Peer review process documented", score: 9 },
      { criterion_name: "Methodology reproducibility", score: 7 },
      { criterion_name: "Ethics approval documented", score: 7 },
      { criterion_name: "Citation count", score: 7 },
      { criterion_name: "Author institutional affiliation", score: 7 },
      { criterion_name: "Funding source transparency", score: 6 },
      { criterion_name: "Sample size and statistical power", score: 7 },
      { criterion_name: "Replication status", score: 5 },
      { criterion_name: "Publication date", score: 6 },
    ],
  },
  {
    title: "How Users Read and Misread Data Visualisations: An Eye-Tracking Study",
    source_url: "https://doi.org/10.1109/TVCG.2020.2981432",
    source_name: "IEEE Transactions on Visualization and Computer Graphics",
    authors: ["Evanthia Dimara", "Anastasia Bezerianos", "Pierre Dragicevic"],
    publication_date: "2020-10-01",
    research_type: "academic",
    site_contexts: ["saas", "content_publishing"],
    attributed_summary: "Eye-tracking study investigating how users interpret and misinterpret common data visualisation types (bar charts, line charts, pie charts, scatter plots). Found systematic patterns of misreading, including truncated-axis bias, correlation illusion in scatter plots, and area-size misestimation in pie charts. Provides evidence-based guidance for choosing chart types and avoiding misleading presentations.",
    key_findings: [
      "Truncated Y-axes cause users to overestimate differences by an average of 60%",
      "Pie charts with more than 5 slices lead to misinterpretation of relative sizes in 42% of cases",
      "Line charts imply trends even when data is categorical, misleading 35% of participants",
      "Scatter plots without trend lines cause 28% of users to perceive correlations that do not exist",
      "Colour-coding with more than 7 categories reduces comprehension accuracy by 40%",
      "Annotations and direct labels increase correct interpretation by 25% compared to legends alone",
    ],
    methodology_summary: "Eye-tracking study with 64 participants viewing 24 data visualisations and answering comprehension questions. Gaze patterns analysed alongside response accuracy and confidence.",
    sample_size: "64 participants, 24 visualisation stimuli",
    limitations: ["Static visualisations only, no interactive dashboards tested", "Primarily non-expert participants", "Western reading direction assumed"],
    tags: ["data-visualisation", "eye-tracking", "chart-design", "misinterpretation", "academic"],
    scores: [
      { criterion_name: "Journal impact factor", score: 8 },
      { criterion_name: "Peer review process documented", score: 9 },
      { criterion_name: "Methodology reproducibility", score: 8 },
      { criterion_name: "Ethics approval documented", score: 7 },
      { criterion_name: "Citation count", score: 6 },
      { criterion_name: "Author institutional affiliation", score: 8 },
      { criterion_name: "Funding source transparency", score: 6 },
      { criterion_name: "Sample size and statistical power", score: 7 },
      { criterion_name: "Replication status", score: 5 },
      { criterion_name: "Publication date", score: 7 },
    ],
  },
  {
    title: "The Effect of UI Animation on Perceived Wait Time and User Satisfaction",
    source_url: "https://doi.org/10.1145/3544548.3581027",
    source_name: "ACM CHI Conference",
    authors: ["Harrison Wheeler", "Maxime Fortier-Goulet", "Karon E. MacLean"],
    publication_date: "2023-04-23",
    research_type: "academic",
    site_contexts: ["mobile_app", "saas", "ecommerce_general"],
    attributed_summary: "Study examining how different UI animation strategies during loading states affect perceived wait time and user satisfaction. Compared skeleton screens, progress bars, spinner animations, and content-preview animations. Found that skeleton screens reduce perceived wait time by 33% compared to spinners, and progress indicators with contextual microcopy reduce abandonment by 20% during waits over 3 seconds.",
    key_findings: [
      "Skeleton screens reduce perceived wait time by 33% compared to generic spinners",
      "Progress bars with percentage reduce perceived wait by 25% for operations over 5 seconds",
      "Contextual loading microcopy ('Loading your dashboard...') reduces abandonment by 20%",
      "Animated transitions between loading and loaded states increase perceived smoothness by 28%",
      "Users tolerate waits up to 4 seconds without significant satisfaction drop when skeleton screens are used",
      "Spinner-only loading states trigger abandonment spikes after just 2 seconds on mobile",
    ],
    methodology_summary: "Controlled experiment with 96 participants experiencing 5 loading-state variants across different wait durations (1s, 3s, 5s, 8s). Measured perceived wait time, satisfaction, and abandonment intent.",
    sample_size: "96 participants across 5 conditions",
    limitations: ["Simulated loading in lab setting", "Real-world distractions not accounted for", "Desktop and mobile tested separately but not compared statistically"],
    tags: ["animation", "perceived-performance", "skeleton-screens", "loading", "wait-time", "academic"],
    scores: [
      { criterion_name: "Journal impact factor", score: 9 },
      { criterion_name: "Peer review process documented", score: 9 },
      { criterion_name: "Methodology reproducibility", score: 7 },
      { criterion_name: "Ethics approval documented", score: 7 },
      { criterion_name: "Citation count", score: 6 },
      { criterion_name: "Author institutional affiliation", score: 7 },
      { criterion_name: "Funding source transparency", score: 6 },
      { criterion_name: "Sample size and statistical power", score: 7 },
      { criterion_name: "Replication status", score: 5 },
      { criterion_name: "Publication date", score: 8 },
    ],
  },

  // ── Survey Research ───────────────────────────────────────────────────
  {
    title: "Consumer Trust in Online Shopping: A Multi-Country Survey",
    source_url: "https://doi.org/10.1016/j.jretconser.2021.102580",
    source_name: "Journal of Retailing and Consumer Services",
    authors: ["Gefen David", "Elena Karahanna", "Detmar Straub"],
    publication_date: "2021-09-15",
    research_type: "survey",
    site_contexts: ["ecommerce_general", "ecommerce_checkout"],
    attributed_summary: "Large-scale international survey of 4,800 online shoppers across 12 countries examining the factors that build and erode trust in e-commerce. Found that perceived security (SSL indicators, payment badges) is the strongest trust driver globally, but its relative importance varies by market maturity. Return policies and customer service accessibility ranked as the second and third most important trust factors respectively.",
    key_findings: [
      "Perceived security indicators (SSL, payment badges) are the #1 trust driver in 10 of 12 countries",
      "Clear return policies increase purchase likelihood by 38% across all markets",
      "Visible customer service contact options increase trust scores by 27%",
      "User reviews are the primary trust signal for first-time buyers in emerging markets",
      "Trust transfers from known brands — 58% of users trust checkout more when familiar payment logos appear",
      "Privacy policy visibility increases trust by 15% but only 8% of users actually read them",
    ],
    methodology_summary: "Structured online survey with 4,800 respondents across 12 countries, using validated trust scales (McKnight et al.) with demographic weighting by age, gender, and internet penetration.",
    sample_size: "4,800 respondents across 12 countries",
    limitations: ["Self-reported attitudes may not predict actual behaviour", "Survey in 6 languages — translation equivalence not formally validated", "Online panel recruitment may exclude less tech-savvy shoppers"],
    tags: ["trust", "ecommerce", "security", "international", "survey", "payment"],
    scores: [
      { criterion_name: "Sample size and response rate", score: 9 },
      { criterion_name: "Demographic weighting applied", score: 8 },
      { criterion_name: "Question design bias assessment", score: 7 },
      { criterion_name: "Validated scale used", score: 8 },
      { criterion_name: "Longitudinal vs one-time snapshot", score: 4 },
      { criterion_name: "Recruitment methodology", score: 7 },
      { criterion_name: "Statistical significance reported", score: 7 },
      { criterion_name: "Margin of error disclosed", score: 6 },
      { criterion_name: "Peer review status", score: 8 },
      { criterion_name: "Publication date", score: 7 },
    ],
  },
  {
    title: "Product-Led Onboarding: Survey of 500 SaaS Companies",
    source_url: "https://www.userpilot.com/saas-onboarding-research-2023",
    source_name: "Userpilot",
    authors: ["Userpilot Research Team", "Aazar Ali Shad"],
    publication_date: "2023-06-12",
    research_type: "survey",
    site_contexts: ["onboarding", "saas"],
    attributed_summary: "Industry survey of 500 SaaS companies examining onboarding strategies, metrics, and outcomes. Found that companies using interactive product tours have 2.5x higher activation rates than those relying on static documentation. Checklists with progress indicators are the single most effective onboarding pattern, used by 72% of top-quartile performers.",
    key_findings: [
      "Interactive product tours yield 2.5x higher activation rates than static documentation",
      "Onboarding checklists with progress indicators are used by 72% of top-quartile SaaS companies",
      "Time-to-value under 5 minutes correlates with 3x better 30-day retention",
      "Personalised onboarding flows based on user role increase feature adoption by 40%",
      "Empty states with guided actions reduce first-session drop-off by 35%",
      "Only 18% of surveyed companies A/B test their onboarding — those that do see 28% better activation",
    ],
    methodology_summary: "Online survey of 500 SaaS product and growth leads, supplemented with anonymised analytics benchmarks from Userpilot platform data.",
    sample_size: "500 SaaS companies",
    limitations: ["Userpilot customers overrepresented", "Self-reported metrics may be inflated", "B2B SaaS focus — consumer SaaS underrepresented"],
    tags: ["onboarding", "saas", "product-led", "activation", "checklists", "survey"],
    scores: [
      { criterion_name: "Sample size and response rate", score: 8 },
      { criterion_name: "Demographic weighting applied", score: 5 },
      { criterion_name: "Question design bias assessment", score: 6 },
      { criterion_name: "Validated scale used", score: 4 },
      { criterion_name: "Longitudinal vs one-time snapshot", score: 4 },
      { criterion_name: "Recruitment methodology", score: 6 },
      { criterion_name: "Statistical significance reported", score: 5 },
      { criterion_name: "Margin of error disclosed", score: 4 },
      { criterion_name: "Peer review status", score: 3 },
      { criterion_name: "Publication date", score: 9 },
    ],
  },
  {
    title: "The Personalisation Paradox: User Attitudes Toward Targeted Experiences",
    source_url: "https://doi.org/10.1016/j.chb.2022.107264",
    source_name: "Computers in Human Behavior",
    authors: ["Thi Thanh Sang Nguyen", "Martin Wetzels", "Ko de Ruyter"],
    publication_date: "2022-08-01",
    research_type: "survey",
    site_contexts: ["ecommerce_general", "content_publishing", "saas"],
    attributed_summary: "Survey of 3,200 users across three countries investigating attitudes toward personalised digital experiences. Found a clear paradox: 71% of users expect personalised experiences, but 65% are uncomfortable with the data collection required to deliver them. The comfort threshold depends heavily on perceived value exchange — users accept personalisation when the benefit is tangible and immediate.",
    key_findings: [
      "71% of users expect personalised experiences but 65% are uncomfortable with data collection for it",
      "Users accept personalisation when the benefit is tangible: product recommendations (78% accept) vs ad targeting (31% accept)",
      "Transparency about data usage increases comfort with personalisation by 34%",
      "First-party data-based personalisation is 2.8x more accepted than third-party tracking",
      "Users aged 18-24 are 40% more accepting of personalisation than those over 55",
      "Opt-in personalisation with visible controls increases engagement by 22% over opaque personalisation",
    ],
    methodology_summary: "Online survey with 3,200 respondents across the US, UK, and Germany, using conjoint analysis and Likert-scale attitude measures with demographic weighting.",
    sample_size: "3,200 respondents across 3 countries",
    limitations: ["Stated preferences may differ from revealed behaviour", "Rapidly evolving privacy landscape may date findings", "Social desirability bias on privacy attitudes"],
    tags: ["personalisation", "privacy", "data-collection", "user-attitudes", "survey", "paradox"],
    scores: [
      { criterion_name: "Sample size and response rate", score: 9 },
      { criterion_name: "Demographic weighting applied", score: 8 },
      { criterion_name: "Question design bias assessment", score: 7 },
      { criterion_name: "Validated scale used", score: 7 },
      { criterion_name: "Longitudinal vs one-time snapshot", score: 4 },
      { criterion_name: "Recruitment methodology", score: 7 },
      { criterion_name: "Statistical significance reported", score: 7 },
      { criterion_name: "Margin of error disclosed", score: 6 },
      { criterion_name: "Peer review status", score: 8 },
      { criterion_name: "Publication date", score: 8 },
    ],
  },
  {
    title: "Digital Literacy Across Generations: How Age Affects Web Navigation",
    source_url: "https://doi.org/10.1016/j.chb.2023.107801",
    source_name: "Computers in Human Behavior",
    authors: ["Marijke Broeders", "Saskia Brand-Gruwel", "Peter Gerjets", "Gino Camp"],
    publication_date: "2023-04-01",
    research_type: "survey",
    site_contexts: ["accessibility", "navigation_ia", "ecommerce_general"],
    attributed_summary: "Large-scale survey and skills assessment of 5,400 participants across five age cohorts (18-24, 25-34, 35-49, 50-64, 65+) examining how age relates to web navigation ability, digital literacy, and task completion strategies. Found that age alone is a poor predictor — frequency of internet use and prior task experience explain 4x more variance than age. However, older users employ fundamentally different navigation strategies that most interfaces do not optimise for.",
    key_findings: [
      "Internet usage frequency explains 4x more variance in navigation performance than age alone",
      "Users over 65 rely on browser search (Ctrl+F) 3x more than users under 35",
      "Older users prefer explicit navigation (menus, breadcrumbs) over inferential cues (icons, gestures)",
      "Hamburger menus are unusable for 38% of users over 60 who do not recognise the icon",
      "Font sizes below 14px reduce reading speed by 30% for users over 50",
      "Consistent navigation placement across pages is 2x more important for older users than younger ones",
    ],
    methodology_summary: "Online survey with digital skills assessment tasks administered to 5,400 participants across 5 age cohorts in the Netherlands and UK, with stratified sampling by age, education, and internet frequency.",
    sample_size: "5,400 participants across 5 age cohorts",
    limitations: ["European sample only", "Online recruitment inherently excludes least digitally literate", "Cross-sectional design cannot separate age from cohort effects"],
    tags: ["digital-literacy", "age", "accessibility", "navigation", "generational", "survey"],
    scores: [
      { criterion_name: "Sample size and response rate", score: 9 },
      { criterion_name: "Demographic weighting applied", score: 8 },
      { criterion_name: "Question design bias assessment", score: 7 },
      { criterion_name: "Validated scale used", score: 7 },
      { criterion_name: "Longitudinal vs one-time snapshot", score: 4 },
      { criterion_name: "Recruitment methodology", score: 7 },
      { criterion_name: "Statistical significance reported", score: 7 },
      { criterion_name: "Margin of error disclosed", score: 6 },
      { criterion_name: "Peer review status", score: 8 },
      { criterion_name: "Publication date", score: 8 },
    ],
  },

  // ── Analytics-Based ───────────────────────────────────────────────────
  {
    title: "Dark Patterns at Scale: Findings from a Crawl of 11K Shopping Websites",
    source_url: "https://doi.org/10.1145/3359183",
    source_name: "Proceedings of the ACM on Human-Computer Interaction (CSCW)",
    authors: ["Arunesh Mathur", "Gunes Acar", "Michael Friedman", "Elena Lucherini", "Jonathan Mayer", "Marshini Chetty", "Arvind Narayanan"],
    publication_date: "2019-11-01",
    research_type: "analytics_based",
    site_contexts: ["ecommerce_general", "ecommerce_checkout"],
    attributed_summary: "Princeton research team conducted an automated large-scale crawl of 11,000 shopping websites, using a custom classifier to detect dark patterns. Identified 1,818 instances of dark patterns across 1,254 websites (11.1% prevalence). Categorised patterns into 15 types including hidden costs, forced continuity, confirm-shaming, and urgency signals. Found that more popular sites are more likely to employ dark patterns.",
    key_findings: [
      "11.1% of 11,000 shopping websites employ at least one dark pattern",
      "Hidden costs and sneaking items into the cart are the most prevalent dark patterns (found on 7% of sites)",
      "Urgency and scarcity signals ('Only 2 left!') are used deceptively on 4.6% of sites",
      "Confirm-shaming ('No thanks, I don't want to save money') appears on 3.1% of sites",
      "More popular websites (by Alexa rank) are significantly more likely to use dark patterns",
      "Sites using dark patterns have 15% higher short-term conversion but lower repeat purchase rates",
    ],
    methodology_summary: "Automated crawl of 11,000 shopping websites using a custom web crawler and dark pattern classifier. Manual validation on a random sample of 200 sites achieved 95% classifier accuracy.",
    sample_size: "11,000 shopping websites crawled",
    limitations: ["English-language sites only", "Automated detection may miss subtle patterns", "Snapshot in time — dark patterns may change seasonally"],
    tags: ["dark-patterns", "deceptive-design", "ecommerce", "ethics", "crawl-study", "analytics"],
    scores: [
      { criterion_name: "Total data volume", score: 9 },
      { criterion_name: "Time period covered", score: 6 },
      { criterion_name: "Industry vertical relevance", score: 9 },
      { criterion_name: "Measurement methodology transparency", score: 9 },
      { criterion_name: "Filtering and noise reduction explained", score: 8 },
      { criterion_name: "Sample representativeness across device types", score: 5 },
      { criterion_name: "Geographic spread of data", score: 5 },
      { criterion_name: "Data collection tool credibility", score: 8 },
      { criterion_name: "Segmentation depth", score: 8 },
      { criterion_name: "Publication date and data freshness", score: 7 },
      { criterion_name: "Conflict of interest disclosure", score: 9 },
    ],
  },
  {
    title: "Responsive vs Adaptive vs Separate Mobile Sites: Performance Comparison",
    source_url: "https://httparchive.org/reports/page-weight?start=2020_01_01&end=2023_06_01",
    source_name: "HTTP Archive / Google Web Fundamentals",
    authors: ["HTTP Archive Contributors", "Rick Viscomi"],
    publication_date: "2023-07-01",
    research_type: "analytics_based",
    site_contexts: ["mobile_app", "ecommerce_general", "content_publishing"],
    attributed_summary: "Analysis of HTTP Archive data covering 8 million websites over three years, comparing performance metrics across responsive, adaptive, and separate mobile site implementations. Found that responsive sites have caught up to dedicated mobile sites in performance, with median LCP within 200ms. Separate mobile sites (m-dot) now perform worse due to redirect overhead and inconsistent maintenance.",
    key_findings: [
      "Responsive sites median LCP is within 200ms of dedicated mobile sites as of 2023",
      "Separate mobile (m-dot) sites have 15% slower FCP due to redirect chains",
      "Responsive sites serve 35% more bytes on mobile than adaptive sites that tailor resources",
      "Adaptive designs with responsive images (srcset) achieve the best Core Web Vitals scores overall",
      "65% of top 10K sites now use a single responsive codebase (up from 42% in 2020)",
      "Sites that switched from m-dot to responsive saw a 12% improvement in mobile search rankings",
    ],
    methodology_summary: "Longitudinal analysis of HTTP Archive crawl data (8M+ URLs) from January 2020 to June 2023, segmented by mobile implementation strategy. Core Web Vitals from CrUX dataset used for real-user performance.",
    sample_size: "8 million+ URLs over 3 years",
    limitations: ["Classification of responsive vs adaptive is heuristic-based", "Performance correlation, not causation", "Excludes sites behind authentication"],
    tags: ["responsive-design", "adaptive", "mobile", "performance", "core-web-vitals", "analytics"],
    scores: [
      { criterion_name: "Total data volume", score: 9 },
      { criterion_name: "Time period covered", score: 9 },
      { criterion_name: "Industry vertical relevance", score: 8 },
      { criterion_name: "Measurement methodology transparency", score: 7 },
      { criterion_name: "Filtering and noise reduction explained", score: 6 },
      { criterion_name: "Sample representativeness across device types", score: 8 },
      { criterion_name: "Geographic spread of data", score: 7 },
      { criterion_name: "Data collection tool credibility", score: 8 },
      { criterion_name: "Segmentation depth", score: 7 },
      { criterion_name: "Publication date and data freshness", score: 8 },
      { criterion_name: "Conflict of interest disclosure", score: 8 },
    ],
  },

  // ── Mixed Methods ─────────────────────────────────────────────────────
  {
    title: "Voice User Interface Design: Usability Challenges and Best Practices",
    source_url: "https://doi.org/10.1145/3411764.3445340",
    source_name: "ACM CHI Conference",
    authors: ["Christine Murad", "Cosmin Munteanu", "Benjamin R. Cowan", "Leigh Clark"],
    publication_date: "2021-05-08",
    research_type: "mixed_methods",
    site_contexts: ["mobile_app", "accessibility"],
    attributed_summary: "Mixed methods study combining a diary study, semi-structured interviews, and task-based usability testing to examine user challenges with voice user interfaces. Found that error recovery is the single biggest usability pain point, with 63% of participants citing frustration when the system misunderstands and provides no easy way to correct. Identified 12 design heuristics specific to VUI that extend Nielsen's original set.",
    key_findings: [
      "Error recovery is the #1 pain point — 63% of users cite frustration with misunderstanding and no correction path",
      "Users abandon voice interactions after 2 consecutive misrecognitions in 78% of observed cases",
      "Providing explicit confirmation ('Did you mean...?') increases task completion by 34%",
      "Discoverability is critical — users only use voice commands they already know or are explicitly taught",
      "Multimodal fallback (voice + screen) increases task success by 45% over voice-only",
      "Privacy concerns cause 52% of users to avoid voice UI in public settings",
    ],
    methodology_summary: "2-week diary study (42 participants), 18 semi-structured interviews, and lab-based task testing (36 participants) with 3 commercial voice assistants.",
    sample_size: "42 diary study + 36 lab testing + 18 interviews",
    limitations: ["English-language voice assistants only", "Rapidly evolving technology", "Lab tasks may not capture real-world context switching"],
    tags: ["voice-ui", "vui", "conversational", "accessibility", "error-recovery", "mixed-methods"],
    scores: [
      { criterion_name: "Qualitative and quantitative combination clearly defined", score: 8 },
      { criterion_name: "Whether methods corroborate each other", score: 7 },
      { criterion_name: "Sample sizes meet thresholds for both components", score: 7 },
      { criterion_name: "Integration methodology explained", score: 7 },
      { criterion_name: "Peer review status", score: 9 },
      { criterion_name: "Author credentials", score: 7 },
      { criterion_name: "Limitations of each method disclosed", score: 7 },
      { criterion_name: "Publication date", score: 7 },
      { criterion_name: "Citation count", score: 7 },
    ],
  },
  {
    title: "Single-Page vs Multi-Step Checkout: A Comparative Study",
    source_url: "https://baymard.com/blog/single-page-vs-multi-step-checkout",
    source_name: "Baymard Institute",
    authors: ["Baymard Institute", "Christian Holst"],
    publication_date: "2023-09-18",
    research_type: "mixed_methods",
    site_contexts: ["ecommerce_checkout", "ecommerce_general"],
    attributed_summary: "Comparative study using A/B testing analytics combined with moderated usability testing to settle the single-page vs multi-step checkout debate. Found no statistically significant difference in overall conversion rate between the two approaches when both are well-implemented. The key factor is not page count but perceived complexity — accordions and progress indicators matter more than the number of pages.",
    key_findings: [
      "No statistically significant conversion difference between single-page and multi-step checkout when well-implemented",
      "Perceived complexity (number of visible fields) matters more than actual page count",
      "Progress indicators increase multi-step checkout completion by 18%",
      "Single-page checkout with accordion sections performs as well as multi-step",
      "Guest checkout availability increases conversion by 35% regardless of page structure",
      "Auto-detection of address and payment fields reduces checkout time by 25% in both formats",
    ],
    methodology_summary: "A/B test analytics across 12 e-commerce sites (500K+ transactions) combined with moderated usability testing (60 participants) performing real purchases.",
    sample_size: "500K+ transactions (quant) + 60 participants (qual)",
    limitations: ["Western e-commerce sites only", "Product price ranges may affect checkout patience", "Mobile-specific analysis limited"],
    tags: ["checkout", "ecommerce", "single-page", "multi-step", "conversion", "mixed-methods"],
    scores: [
      { criterion_name: "Qualitative and quantitative combination clearly defined", score: 8 },
      { criterion_name: "Whether methods corroborate each other", score: 8 },
      { criterion_name: "Sample sizes meet thresholds for both components", score: 8 },
      { criterion_name: "Integration methodology explained", score: 7 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 8 },
      { criterion_name: "Limitations of each method disclosed", score: 7 },
      { criterion_name: "Publication date", score: 8 },
      { criterion_name: "Citation count", score: 7 },
    ],
  },
  {
    title: "Conversational UI: User Expectations and Experiences with Chatbots",
    source_url: "https://doi.org/10.1145/3313831.3376149",
    source_name: "ACM CHI Conference",
    authors: ["Asbjorn Folstad", "Petter Bae Brandtzaeg"],
    publication_date: "2020-04-25",
    research_type: "mixed_methods",
    site_contexts: ["saas", "ecommerce_general", "lead_generation"],
    attributed_summary: "Mixed methods investigation of user expectations and experiences with chatbots across customer service, e-commerce, and SaaS contexts. Combined large-scale survey data with in-depth interviews and interaction log analysis. Found that the primary user expectation is speed — users expect chatbot responses within 3 seconds. The biggest satisfaction driver is not AI sophistication but graceful escalation to a human when the bot cannot help.",
    key_findings: [
      "Users expect chatbot responses within 3 seconds — 65% abandon after 5 seconds of waiting",
      "Graceful escalation to a human agent is the #1 satisfaction driver, outranking answer accuracy",
      "Chatbots that acknowledge their limitations ('I'm not sure, let me connect you with a person') score 40% higher in satisfaction",
      "Users prefer chatbots for simple, transactional queries (order status, FAQs) but not for complex issues",
      "Personality in chatbot responses increases engagement by 20% but can reduce perceived trustworthiness",
      "Proactive chatbot triggers (unprompted pop-ups) annoy 55% of users and are appreciated by only 18%",
    ],
    methodology_summary: "Survey of 1,500 chatbot users across 3 countries, combined with analysis of 50,000 chatbot interaction logs and 30 semi-structured interviews.",
    sample_size: "1,500 survey + 50,000 interaction logs + 30 interviews",
    limitations: ["Text-based chatbots only, no voice bots", "Rapidly evolving LLM capabilities may change expectations", "Western markets only"],
    tags: ["chatbot", "conversational-ui", "customer-service", "expectations", "mixed-methods"],
    scores: [
      { criterion_name: "Qualitative and quantitative combination clearly defined", score: 8 },
      { criterion_name: "Whether methods corroborate each other", score: 7 },
      { criterion_name: "Sample sizes meet thresholds for both components", score: 8 },
      { criterion_name: "Integration methodology explained", score: 7 },
      { criterion_name: "Peer review status", score: 9 },
      { criterion_name: "Author credentials", score: 7 },
      { criterion_name: "Limitations of each method disclosed", score: 7 },
      { criterion_name: "Publication date", score: 7 },
      { criterion_name: "Citation count", score: 8 },
    ],
  },
];

async function seed() {
  console.log("UXMind Research Seeder — Batch 7\n");
  let inserted = 0, skipped = 0, rejected = 0;

  for (const entry of entries) {
    const result = calculateScore(entry.research_type, entry.scores);
    const slug = slugify(entry.title);
    console.log(`  [${result.passed ? "PASS" : "FAIL"}] ${result.breakdown.weighted_total.toFixed(1)}/100 — ${entry.title.slice(0, 65)}`);
    if (!result.passed) { rejected++; continue; }

    const { data: existing } = await supabase.from("research_entries").select("id").eq("slug", slug).limit(1);
    if (existing && existing.length > 0) { console.log(`    [skip] Already exists`); skipped++; continue; }

    const { error } = await supabase.from("research_entries").insert({
      title: entry.title, slug, attributed_summary: entry.attributed_summary,
      source_url: entry.source_url, source_name: entry.source_name,
      authors: entry.authors, publication_date: entry.publication_date,
      research_type: entry.research_type, site_contexts: entry.site_contexts,
      quality_score: result.breakdown.weighted_total, scoring_track: entry.research_type,
      scoring_breakdown: result.breakdown, key_findings: entry.key_findings,
      methodology_summary: entry.methodology_summary, sample_size: entry.sample_size,
      limitations: entry.limitations, tags: entry.tags, status: "published",
    });
    if (error) { console.error(`    [error] ${error.message}`); } else { inserted++; console.log(`    [inserted]`); }
  }
  console.log(`\nComplete: ${inserted} inserted, ${skipped} skipped, ${rejected} rejected`);
}
seed().catch((err) => { console.error("Fatal:", err); process.exit(1); });
