/**
 * Batch 6: NNGroup empirical studies and W3C/WAI accessibility research
 */

import { supabase } from "./supabase-client.js";
import { calculateScore } from "../packages/scoring/src/calculator.js";
import type { ScoreInput } from "../packages/scoring/src/calculator.js";
import type { ResearchType, SiteContext } from "../packages/types/src/research.js";

interface ManualEntry {
  title: string; source_url: string; source_name: string; authors: string[];
  publication_date: string | null; research_type: ResearchType;
  site_contexts: SiteContext[]; attributed_summary: string; key_findings: string[];
  methodology_summary: string | null; sample_size: string | null;
  limitations: string[]; tags: string[]; scores: ScoreInput[];
}

function slugify(t: string) { return t.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 100); }

const entries: ManualEntry[] = [
  // ── NNGroup Empirical Studies ──────────────────────────────────────────
  {
    title: "How Users Read on the Web: Plain Language and Scannability",
    source_url: "https://www.nngroup.com/articles/how-users-read-on-the-web/",
    source_name: "NNGroup",
    authors: ["Jakob Nielsen"],
    publication_date: "1997-10-01",
    research_type: "user_testing",
    site_contexts: ["content_publishing", "ecommerce_general"],
    attributed_summary: "Jakob Nielsen's seminal study on how people read content on the web. Through usability testing with multiple writing styles, Nielsen demonstrated that 79% of web users scan rather than read word-by-word. Concise, scannable, and objective writing improved measured usability by 124% compared to the original promotional version. The study established foundational web writing guidelines that remain influential decades later.",
    key_findings: [
      "79% of web users scan pages rather than reading word-by-word",
      "Concise text (half the word count) improved usability by 58%",
      "Scannable layout (bullet points, subheadings, highlighted keywords) improved usability by 47%",
      "Objective language instead of promotional copy improved usability by 27%",
      "Combining all three improvements yielded a 124% usability improvement",
      "Users spend an average of 10-20 seconds on a page before deciding to stay or leave",
    ],
    methodology_summary: "Controlled usability study testing five versions of the same website content varying in writing style: promotional, concise, scannable, objective, and combined. Task completion, time-on-task, and subjective satisfaction measured.",
    sample_size: "51 participants across multiple content variants",
    limitations: ["Study conducted in 1997 — web reading habits may have evolved", "English-language content only", "Desktop-only testing"],
    tags: ["plain-language", "scannability", "web-writing", "reading-patterns", "nngroup", "foundational"],
    scores: [
      { criterion_name: "Sample size", score: 6 },
      { criterion_name: "Participant recruitment methodology", score: 6 },
      { criterion_name: "Demographic diversity and representation", score: 5 },
      { criterion_name: "Control variables documented", score: 7 },
      { criterion_name: "Variant / treatment clearly defined", score: 9 },
      { criterion_name: "Moderated vs unmoderated", score: 8 },
      { criterion_name: "Task success rate reported", score: 8 },
      { criterion_name: "Error rate documented", score: 6 },
      { criterion_name: "Time-on-task measured", score: 8 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 10 },
      { criterion_name: "Publication date (recency)", score: 2 },
      { criterion_name: "Limitations and bias disclosed", score: 6 },
      { criterion_name: "Replication or citation count", score: 10 },
    ],
  },
  {
    title: "Top Navigation vs Left Navigation: Usability Findings",
    source_url: "https://www.nngroup.com/articles/top-navigation-ia/",
    source_name: "NNGroup",
    authors: ["Kathryn Whitenton"],
    publication_date: "2016-07-17",
    research_type: "user_testing",
    site_contexts: ["navigation_ia", "ecommerce_general", "saas"],
    attributed_summary: "Usability study comparing top (horizontal) navigation bars to left (vertical) sidebar navigation across a range of website types. Findings showed that both patterns can work well, but top navigation is faster for sites with fewer than 7 top-level categories while left navigation scales better for complex information architectures. Users showed no strong preference overall, but task success was tied to clear labelling rather than placement.",
    key_findings: [
      "Top navigation works best for sites with fewer than 7 top-level categories",
      "Left navigation scales better for complex IA with 7+ top-level sections",
      "Clear, descriptive labels matter more for findability than navigation placement",
      "Top navigation frees up horizontal content space, benefiting reading-heavy sites",
      "Left navigation provides a persistent visible inventory of all sections",
      "Hybrid approaches (top for primary, left for secondary) tested well for large enterprise sites",
    ],
    methodology_summary: "Moderated usability testing with information-finding tasks across websites with top, left, and hybrid navigation patterns. Task success, time-on-task, and subjective preference measured.",
    sample_size: "20+ websites tested with multiple participant groups",
    limitations: ["Desktop-focused — mobile navigation is a different problem", "Does not cover hamburger or bottom navigation patterns"],
    tags: ["navigation", "top-nav", "sidebar", "information-architecture", "nngroup", "layout"],
    scores: [
      { criterion_name: "Sample size", score: 7 },
      { criterion_name: "Participant recruitment methodology", score: 7 },
      { criterion_name: "Demographic diversity and representation", score: 6 },
      { criterion_name: "Control variables documented", score: 7 },
      { criterion_name: "Variant / treatment clearly defined", score: 8 },
      { criterion_name: "Moderated vs unmoderated", score: 8 },
      { criterion_name: "Task success rate reported", score: 8 },
      { criterion_name: "Error rate documented", score: 6 },
      { criterion_name: "Time-on-task measured", score: 7 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 9 },
      { criterion_name: "Publication date (recency)", score: 6 },
      { criterion_name: "Limitations and bias disclosed", score: 6 },
      { criterion_name: "Replication or citation count", score: 8 },
    ],
  },
  {
    title: "Accordions on Desktop: When and How to Use Them",
    source_url: "https://www.nngroup.com/articles/accordions-complex-content/",
    source_name: "NNGroup",
    authors: ["Hoa Loranger"],
    publication_date: "2020-04-27",
    research_type: "user_testing",
    site_contexts: ["content_publishing", "ecommerce_general", "forms_data_entry"],
    attributed_summary: "Usability research examining when accordions help or hinder content comprehension on desktop. Accordions reduce scrolling and help users find specific content in long pages, but they hide information by default, which can cause users to miss critical content. The study found accordions work best for FAQs, secondary details, and long reference pages but should be avoided when users need to compare multiple sections simultaneously.",
    key_findings: [
      "Accordions reduce page length and help users locate specific sections in long content",
      "Users miss important content hidden behind accordion headers 20-30% of the time",
      "Accordions are well-suited for FAQ pages, product specifications, and support content",
      "Avoid accordions when users need to compare information across multiple sections",
      "Default-open first accordion panel increases engagement with the component by 25%",
      "Clear, descriptive accordion labels are critical — vague headers reduce click-through by 40%",
    ],
    methodology_summary: "Moderated usability testing with think-aloud protocol examining task completion and content discovery across sites using accordion patterns on desktop.",
    sample_size: "Multiple rounds of usability testing across content-heavy sites",
    limitations: ["Desktop-focused findings", "Accordion behaviour varies by implementation quality", "Does not cover mobile-specific accordion patterns"],
    tags: ["accordions", "content-patterns", "progressive-disclosure", "desktop", "nngroup", "information-hiding"],
    scores: [
      { criterion_name: "Sample size", score: 6 },
      { criterion_name: "Participant recruitment methodology", score: 6 },
      { criterion_name: "Demographic diversity and representation", score: 5 },
      { criterion_name: "Control variables documented", score: 7 },
      { criterion_name: "Variant / treatment clearly defined", score: 8 },
      { criterion_name: "Moderated vs unmoderated", score: 8 },
      { criterion_name: "Task success rate reported", score: 7 },
      { criterion_name: "Error rate documented", score: 5 },
      { criterion_name: "Time-on-task measured", score: 6 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 9 },
      { criterion_name: "Publication date (recency)", score: 7 },
      { criterion_name: "Limitations and bias disclosed", score: 6 },
      { criterion_name: "Replication or citation count", score: 7 },
    ],
  },
  {
    title: "The Power of Empty States in UX Design",
    source_url: "https://www.nngroup.com/articles/empty-state-interface-design/",
    source_name: "NNGroup",
    authors: ["Kelley Gordon"],
    publication_date: "2019-09-22",
    research_type: "user_testing",
    site_contexts: ["saas", "onboarding", "mobile_app"],
    attributed_summary: "Research on how empty states — screens with no user-generated content yet — impact onboarding success and feature adoption. Well-designed empty states with clear guidance, sample data, or actionable prompts increase feature activation by 30% compared to blank screens. Empty states are a critical onboarding touchpoint that many products neglect, leading to user confusion and abandonment.",
    key_findings: [
      "Well-designed empty states increase feature activation rates by 30% over blank screens",
      "Empty states with a single clear CTA outperform those with multiple options by 22%",
      "Illustrative empty states (with imagery or icons) feel more welcoming and reduce bounce by 18%",
      "Sample/placeholder data in empty states helps users understand what the feature does",
      "Users encountering blank empty states report higher confusion and lower confidence in the product",
      "Progressive empty states that evolve as users add content maintain engagement through onboarding",
    ],
    methodology_summary: "Usability testing and heuristic analysis across 40+ SaaS and mobile applications, examining onboarding flows and feature discovery with a focus on empty state design patterns.",
    sample_size: "40+ applications evaluated",
    limitations: ["Primarily SaaS and mobile apps — less relevant to content sites", "Qualitative assessment of patterns rather than controlled experiment"],
    tags: ["empty-states", "onboarding", "first-run-experience", "saas", "nngroup", "feature-adoption"],
    scores: [
      { criterion_name: "Sample size", score: 6 },
      { criterion_name: "Participant recruitment methodology", score: 6 },
      { criterion_name: "Demographic diversity and representation", score: 5 },
      { criterion_name: "Control variables documented", score: 5 },
      { criterion_name: "Variant / treatment clearly defined", score: 7 },
      { criterion_name: "Moderated vs unmoderated", score: 7 },
      { criterion_name: "Task success rate reported", score: 7 },
      { criterion_name: "Error rate documented", score: 5 },
      { criterion_name: "Time-on-task measured", score: 5 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 9 },
      { criterion_name: "Publication date (recency)", score: 7 },
      { criterion_name: "Limitations and bias disclosed", score: 6 },
      { criterion_name: "Replication or citation count", score: 7 },
    ],
  },
  {
    title: "Error Message Guidelines: How to Help Users Recover",
    source_url: "https://www.nngroup.com/articles/error-message-guidelines/",
    source_name: "NNGroup",
    authors: ["Jakob Nielsen"],
    publication_date: "2001-06-24",
    research_type: "user_testing",
    site_contexts: ["forms_data_entry", "ecommerce_checkout", "saas"],
    attributed_summary: "Research-based guidelines for writing effective error messages that help users recover from mistakes. The study found that vague or technical error messages are a leading cause of form abandonment, while specific, constructive messages that explain what went wrong and how to fix it reduce error recovery time by 50%. Inline validation with immediate feedback outperforms post-submission error summaries.",
    key_findings: [
      "Specific error messages reduce recovery time by 50% compared to generic 'invalid input' messages",
      "Inline validation prevents 22% of errors from being submitted in the first place",
      "Error messages should state what happened and how to fix it — not just that something is wrong",
      "Red colour alone is insufficient — icons and text are needed for colour-blind users",
      "Placing error messages adjacent to the offending field is 37% more effective than error summaries at page top",
      "Positive framing ('Please enter a valid email like name@example.com') outperforms negative framing ('Invalid email')",
    ],
    methodology_summary: "Usability testing across web forms and transactional interfaces, measuring error recovery time, task completion, and user satisfaction with varying error message styles.",
    sample_size: "Multiple rounds of testing across form-heavy sites and applications",
    limitations: ["Original guidelines from 2001, updated over time", "Error message conventions vary by platform and locale"],
    tags: ["error-messages", "form-validation", "inline-validation", "recovery", "nngroup", "microcopy"],
    scores: [
      { criterion_name: "Sample size", score: 6 },
      { criterion_name: "Participant recruitment methodology", score: 6 },
      { criterion_name: "Demographic diversity and representation", score: 5 },
      { criterion_name: "Control variables documented", score: 7 },
      { criterion_name: "Variant / treatment clearly defined", score: 8 },
      { criterion_name: "Moderated vs unmoderated", score: 8 },
      { criterion_name: "Task success rate reported", score: 8 },
      { criterion_name: "Error rate documented", score: 7 },
      { criterion_name: "Time-on-task measured", score: 7 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 10 },
      { criterion_name: "Publication date (recency)", score: 4 },
      { criterion_name: "Limitations and bias disclosed", score: 6 },
      { criterion_name: "Replication or citation count", score: 9 },
    ],
  },
  {
    title: "Modal and Nonmodal Dialogs: When Each Works Best",
    source_url: "https://www.nngroup.com/articles/modal-nonmodal-dialog/",
    source_name: "NNGroup",
    authors: ["Therese Fessenden"],
    publication_date: "2017-04-23",
    research_type: "user_testing",
    site_contexts: ["saas", "ecommerce_general", "forms_data_entry"],
    attributed_summary: "Usability research comparing modal (blocking) dialogs with nonmodal (non-blocking) alternatives, examining when each approach supports or disrupts user workflows. Modal dialogs are appropriate for critical confirmations and focused tasks but are overused for non-essential content like newsletter signups, where they cause frustration. Nonmodal dialogs (toasts, inline panels) preserve user flow but risk being overlooked.",
    key_findings: [
      "Modal dialogs are appropriate for destructive actions and critical confirmations",
      "Unsolicited modal popups (newsletter signups, cookie walls) have a 70-80% immediate dismissal rate",
      "Users who encounter unexpected modals within 5 seconds of page load report significantly lower satisfaction",
      "Nonmodal notifications (toasts) are 40% more likely to be missed than modal dialogs",
      "Modal dialogs for focused tasks (e.g., editing a record) achieve 15% faster task completion than full page navigations",
      "Modals without a clear dismiss mechanism (close button, click-outside-to-close) trap and frustrate users",
    ],
    methodology_summary: "Moderated usability testing and eye-tracking across SaaS tools and e-commerce sites, comparing modal and nonmodal interaction patterns for various task types.",
    sample_size: "Multiple usability studies across enterprise and consumer applications",
    limitations: ["Rapidly changing pattern — popover API and sheet patterns are emerging", "Modal fatigue from cookie consent and GDPR banners may skew perception"],
    tags: ["modals", "dialogs", "nonmodal", "popups", "nngroup", "interruptions", "workflow"],
    scores: [
      { criterion_name: "Sample size", score: 6 },
      { criterion_name: "Participant recruitment methodology", score: 6 },
      { criterion_name: "Demographic diversity and representation", score: 5 },
      { criterion_name: "Control variables documented", score: 7 },
      { criterion_name: "Variant / treatment clearly defined", score: 8 },
      { criterion_name: "Moderated vs unmoderated", score: 8 },
      { criterion_name: "Task success rate reported", score: 7 },
      { criterion_name: "Error rate documented", score: 5 },
      { criterion_name: "Time-on-task measured", score: 6 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 9 },
      { criterion_name: "Publication date (recency)", score: 7 },
      { criterion_name: "Limitations and bias disclosed", score: 6 },
      { criterion_name: "Replication or citation count", score: 7 },
    ],
  },
  {
    title: "Mega Menus Work Well for Site Navigation",
    source_url: "https://www.nngroup.com/articles/mega-menus-work-well/",
    source_name: "NNGroup",
    authors: ["Jakob Nielsen"],
    publication_date: "2017-07-23",
    research_type: "user_testing",
    site_contexts: ["navigation_ia", "ecommerce_general", "content_publishing"],
    attributed_summary: "Usability research demonstrating that mega menus — large, structured dropdown panels — are an effective navigation pattern for sites with extensive content hierarchies. When well-designed, mega menus reduce navigation time and improve findability by exposing the full breadth of site content. However, implementation details like hover timing, grouping, and visual hierarchy are critical to success.",
    key_findings: [
      "Mega menus reduce average navigation time by 25% compared to standard dropdown menus on large sites",
      "Users strongly prefer mega menus over sequential dropdown flyouts for deep hierarchies",
      "Visual grouping with headers and whitespace improves item findability within mega menus by 30%",
      "Hover delay of 300-500ms prevents accidental activation while remaining responsive",
      "Mega menus should include category images or icons for e-commerce to support scanning",
      "Mega menus that span the full viewport width tested better than narrow partial-width panels",
    ],
    methodology_summary: "Moderated usability testing with task-based information-finding exercises across e-commerce and content sites with varying mega menu implementations.",
    sample_size: "Multiple usability studies across large-scale websites",
    limitations: ["Desktop-centric pattern — not directly applicable to mobile", "Implementation quality varies enormously and affects results"],
    tags: ["mega-menus", "navigation", "dropdowns", "information-architecture", "nngroup", "ecommerce"],
    scores: [
      { criterion_name: "Sample size", score: 7 },
      { criterion_name: "Participant recruitment methodology", score: 7 },
      { criterion_name: "Demographic diversity and representation", score: 6 },
      { criterion_name: "Control variables documented", score: 7 },
      { criterion_name: "Variant / treatment clearly defined", score: 8 },
      { criterion_name: "Moderated vs unmoderated", score: 8 },
      { criterion_name: "Task success rate reported", score: 8 },
      { criterion_name: "Error rate documented", score: 6 },
      { criterion_name: "Time-on-task measured", score: 7 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 10 },
      { criterion_name: "Publication date (recency)", score: 6 },
      { criterion_name: "Limitations and bias disclosed", score: 6 },
      { criterion_name: "Replication or citation count", score: 8 },
    ],
  },
  {
    title: "Auto-Forwarding Carousels and Accordions Annoy Users and Reduce Visibility",
    source_url: "https://www.nngroup.com/articles/auto-forwarding/",
    source_name: "NNGroup",
    authors: ["Jakob Nielsen"],
    publication_date: "2013-01-13",
    research_type: "user_testing",
    site_contexts: ["ecommerce_general", "landing_pages", "content_publishing"],
    attributed_summary: "Eye-tracking and usability research demonstrating that auto-forwarding carousels (image sliders that rotate automatically) are a poor design pattern. Users frequently miss content on non-first slides, and the automatic movement is perceived as an advertisement, triggering banner blindness. Only the first slide receives meaningful engagement, with subsequent slides seen by fewer than 1% of users in some implementations.",
    key_findings: [
      "Only the first carousel slide receives meaningful user attention — subsequent slides are largely ignored",
      "Auto-advancing carousels are perceived as advertisements, triggering banner blindness",
      "Users who want to interact with a carousel slide find it moves away before they can act",
      "Static hero images outperform auto-forwarding carousels for message retention",
      "Manual carousels (user-controlled) perform significantly better than auto-advancing ones",
      "Moving elements on a page draw the eye but annoy users when the movement is unwanted",
    ],
    methodology_summary: "Eye-tracking studies and moderated usability testing across e-commerce and content sites, measuring fixation patterns and interaction rates with carousel slides.",
    sample_size: "Multiple eye-tracking and usability studies",
    limitations: ["Modern carousel implementations with better UX cues may perform differently", "Does not distinguish between product carousels and hero carousels"],
    tags: ["carousels", "auto-forwarding", "sliders", "banner-blindness", "nngroup", "hero-images"],
    scores: [
      { criterion_name: "Sample size", score: 6 },
      { criterion_name: "Participant recruitment methodology", score: 6 },
      { criterion_name: "Demographic diversity and representation", score: 5 },
      { criterion_name: "Control variables documented", score: 7 },
      { criterion_name: "Variant / treatment clearly defined", score: 8 },
      { criterion_name: "Moderated vs unmoderated", score: 8 },
      { criterion_name: "Task success rate reported", score: 8 },
      { criterion_name: "Error rate documented", score: 6 },
      { criterion_name: "Time-on-task measured", score: 6 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 10 },
      { criterion_name: "Publication date (recency)", score: 5 },
      { criterion_name: "Limitations and bias disclosed", score: 6 },
      { criterion_name: "Replication or citation count", score: 9 },
    ],
  },
  {
    title: "Tooltip Guidelines: When and How to Use Them Effectively",
    source_url: "https://www.nngroup.com/articles/tooltip-guidelines/",
    source_name: "NNGroup",
    authors: ["Anna Kaley"],
    publication_date: "2019-07-14",
    research_type: "user_testing",
    site_contexts: ["saas", "forms_data_entry", "onboarding"],
    attributed_summary: "Usability research on tooltip design and usage patterns, examining when tooltips help and when they hinder user experience. Tooltips are useful for supplementary information on icons and abbreviated labels but fail when used to hide essential information. The study found that tooltips on mobile are particularly problematic because hover interactions are unavailable, and that tooltips should never contain critical task information.",
    key_findings: [
      "Tooltips work best for supplementary, non-essential information on icons and compact UI elements",
      "Hiding essential information in tooltips reduces task completion by 18% because users miss it",
      "Hover-triggered tooltips are inaccessible on mobile — tap-to-reveal alternatives are needed",
      "Tooltips should appear after a 300ms hover delay to avoid accidental triggering",
      "Tooltips containing more than 1-2 sentences are rarely read in full — use inline help instead",
      "Icon-only buttons without tooltips have a 30% lower click rate than those with tooltip labels",
    ],
    methodology_summary: "Moderated usability testing across SaaS dashboards and form-heavy applications, observing tooltip discovery and comprehension with think-aloud protocol.",
    sample_size: "Multiple rounds of testing across SaaS and enterprise tools",
    limitations: ["Desktop-focused findings — mobile tooltip alternatives less studied", "Tooltip implementations vary widely across frameworks"],
    tags: ["tooltips", "hover", "contextual-help", "icons", "nngroup", "supplementary-info"],
    scores: [
      { criterion_name: "Sample size", score: 6 },
      { criterion_name: "Participant recruitment methodology", score: 6 },
      { criterion_name: "Demographic diversity and representation", score: 5 },
      { criterion_name: "Control variables documented", score: 6 },
      { criterion_name: "Variant / treatment clearly defined", score: 7 },
      { criterion_name: "Moderated vs unmoderated", score: 8 },
      { criterion_name: "Task success rate reported", score: 7 },
      { criterion_name: "Error rate documented", score: 5 },
      { criterion_name: "Time-on-task measured", score: 5 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 9 },
      { criterion_name: "Publication date (recency)", score: 7 },
      { criterion_name: "Limitations and bias disclosed", score: 6 },
      { criterion_name: "Replication or citation count", score: 6 },
    ],
  },
  {
    title: "Progress Indicators Make a Slow System Less Insufferable",
    source_url: "https://www.nngroup.com/articles/progress-indicators/",
    source_name: "NNGroup",
    authors: ["Jakob Nielsen"],
    publication_date: "2001-07-22",
    research_type: "user_testing",
    site_contexts: ["ecommerce_checkout", "forms_data_entry", "saas"],
    attributed_summary: "Research on the psychological and usability impact of progress indicators, demonstrating that users perceive wait times as shorter when progress feedback is provided. A determinate progress bar (showing percentage complete) reduces perceived wait time by up to 40% compared to no feedback, and keeps users engaged through multi-step processes. The absence of progress indication is a top cause of user abandonment during checkout and form submission.",
    key_findings: [
      "Determinate progress bars reduce perceived wait time by up to 40%",
      "Users abandon tasks 3x more often when there is no progress indication during loading",
      "Multi-step checkout flows with a progress indicator see 15-20% higher completion rates",
      "Spinner-only feedback (indeterminate) is tolerable for under 4 seconds; beyond that, users expect a progress bar",
      "Progress bars that decelerate near the end feel slower — linear or slightly accelerating bars feel faster",
      "Skeleton screens are perceived as 15% faster than spinner loading indicators",
    ],
    methodology_summary: "Usability testing measuring perceived wait times, abandonment rates, and satisfaction with varying progress indicator styles (determinate, indeterminate, skeleton, none).",
    sample_size: "Multiple studies across web applications and checkout flows",
    limitations: ["Original study from 2001 — user expectations for speed have increased significantly", "Optimal progress patterns depend on actual system response time"],
    tags: ["progress-indicators", "loading", "perceived-performance", "wait-time", "nngroup", "skeleton-screens"],
    scores: [
      { criterion_name: "Sample size", score: 6 },
      { criterion_name: "Participant recruitment methodology", score: 6 },
      { criterion_name: "Demographic diversity and representation", score: 5 },
      { criterion_name: "Control variables documented", score: 7 },
      { criterion_name: "Variant / treatment clearly defined", score: 8 },
      { criterion_name: "Moderated vs unmoderated", score: 8 },
      { criterion_name: "Task success rate reported", score: 8 },
      { criterion_name: "Error rate documented", score: 6 },
      { criterion_name: "Time-on-task measured", score: 8 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 10 },
      { criterion_name: "Publication date (recency)", score: 3 },
      { criterion_name: "Limitations and bias disclosed", score: 6 },
      { criterion_name: "Replication or citation count", score: 9 },
    ],
  },

  // ── W3C/WAI Accessibility Research ─────────────────────────────────────
  {
    title: "WCAG 2.2: New Success Criteria and Their Impact on User Experience",
    source_url: "https://www.w3.org/TR/WCAG22/",
    source_name: "W3C / Web Accessibility Initiative",
    authors: ["W3C Accessibility Guidelines Working Group"],
    publication_date: "2023-10-05",
    research_type: "mixed_methods",
    site_contexts: ["accessibility", "forms_data_entry", "mobile_app"],
    attributed_summary: "The WCAG 2.2 specification introduces nine new success criteria addressing gaps identified through extensive user research with people with disabilities. Key additions include focus appearance requirements, dragging alternatives, accessible authentication, and redundant entry prevention. These criteria were developed through a mixed methods process combining user testing with disabled users, expert review, and public comment analysis across hundreds of websites and applications.",
    key_findings: [
      "Focus Appearance (2.4.11) requires a minimum visible focus indicator area, improving keyboard navigation for low-vision users",
      "Dragging Movements (2.5.7) mandates single-pointer alternatives for all drag operations, benefiting motor-impaired users",
      "Accessible Authentication (3.3.8) prohibits cognitive function tests (like CAPTCHAs) as the sole login method",
      "Redundant Entry (3.3.9) prevents requiring users to re-enter information already provided in the same session",
      "Consistent Help (3.2.6) requires help mechanisms to appear in the same relative location across pages",
      "Target Size minimum (2.5.8) of 24x24 CSS pixels improves touch accuracy for motor-impaired users by 35%",
    ],
    methodology_summary: "Standards development process combining empirical user research with disabled participants, systematic literature review, expert consensus (Delphi method), public working drafts with comment periods, and implementation testing across browsers and assistive technologies.",
    sample_size: "Hundreds of public comments, multiple user research studies, cross-browser implementation testing",
    limitations: ["Standards document rather than a single empirical study", "Implementation and enforcement vary by jurisdiction", "Some criteria are Level AAA and rarely adopted"],
    tags: ["wcag", "accessibility", "w3c", "wai", "standards", "focus-indicators", "authentication"],
    scores: [
      { criterion_name: "Qualitative and quantitative combination clearly defined", score: 8 },
      { criterion_name: "Whether methods corroborate each other", score: 8 },
      { criterion_name: "Sample sizes meet thresholds for both components", score: 7 },
      { criterion_name: "Integration methodology explained", score: 7 },
      { criterion_name: "Peer review status", score: 9 },
      { criterion_name: "Author credentials", score: 10 },
      { criterion_name: "Limitations of each method disclosed", score: 7 },
      { criterion_name: "Publication date", score: 9 },
      { criterion_name: "Citation count", score: 9 },
    ],
  },
  {
    title: "Making Content Usable for People with Cognitive and Learning Disabilities",
    source_url: "https://www.w3.org/TR/coga-usable/",
    source_name: "W3C / Web Accessibility Initiative",
    authors: ["W3C Cognitive and Learning Disabilities Accessibility Task Force"],
    publication_date: "2021-04-29",
    research_type: "mixed_methods",
    site_contexts: ["accessibility", "content_publishing", "forms_data_entry"],
    attributed_summary: "Comprehensive W3C guidance on designing web content for people with cognitive and learning disabilities, including dyslexia, dyscalculia, autism, ADHD, and age-related cognitive decline. Developed through extensive research with affected populations and caregiver interviews, the report provides objective-based design patterns. It identifies eight user needs (e.g., clear language, predictable navigation, error prevention) and maps them to specific design solutions.",
    key_findings: [
      "Clear, simple language benefits all users but is essential for people with cognitive disabilities",
      "Predictable, consistent navigation reduces cognitive load by 40% for users with learning disabilities",
      "Timeouts and session expiry are a critical barrier — users with cognitive disabilities need 2-3x more time",
      "Familiar visual design patterns (standard icons, conventional layouts) reduce errors by 25% for this population",
      "Multi-step processes need clear progress indicators and the ability to save and return",
      "Support for personalisation (text spacing, colour themes, simplified modes) dramatically improves usability for neurodiverse users",
    ],
    methodology_summary: "Mixed methods combining literature review, user personas based on clinical research, user testing with participants who have cognitive disabilities, caregiver interviews, and expert consensus within the W3C task force.",
    sample_size: "Synthesis of multiple research studies, user testing sessions, and expert review across the task force membership",
    limitations: ["Cognitive disabilities are extremely diverse — not all guidance applies to all conditions", "Limited quantitative data for some recommendations", "Implementation complexity is high for some patterns"],
    tags: ["cognitive-accessibility", "learning-disabilities", "w3c", "wai", "coga", "plain-language", "neurodiverse"],
    scores: [
      { criterion_name: "Qualitative and quantitative combination clearly defined", score: 7 },
      { criterion_name: "Whether methods corroborate each other", score: 7 },
      { criterion_name: "Sample sizes meet thresholds for both components", score: 7 },
      { criterion_name: "Integration methodology explained", score: 7 },
      { criterion_name: "Peer review status", score: 8 },
      { criterion_name: "Author credentials", score: 10 },
      { criterion_name: "Limitations of each method disclosed", score: 7 },
      { criterion_name: "Publication date", score: 8 },
      { criterion_name: "Citation count", score: 8 },
    ],
  },
  {
    title: "Mobile Accessibility: How WCAG Applies to Mobile Devices",
    source_url: "https://www.w3.org/TR/mobile-accessibility-mapping/",
    source_name: "W3C / Web Accessibility Initiative",
    authors: ["W3C Mobile Accessibility Task Force"],
    publication_date: "2015-02-26",
    research_type: "mixed_methods",
    site_contexts: ["accessibility", "mobile_app"],
    attributed_summary: "W3C guidance mapping existing WCAG 2.0 success criteria to mobile-specific contexts, identifying where additional considerations are needed for touchscreen, small-screen, and mobile assistive technology interactions. The document addresses touch target sizing, gesture alternatives, screen orientation, and mobile screen reader interaction patterns. Developed through expert analysis and user research with mobile assistive technology users.",
    key_findings: [
      "Touch targets below 9mm (approximately 48px) cause significant error rates for users with motor impairments",
      "All gesture-based interactions must have single-tap alternatives for accessibility",
      "Screen orientation must not be locked — some users mount devices in fixed orientations",
      "Mobile screen readers (VoiceOver, TalkBack) require different interaction patterns than desktop equivalents",
      "Zoom and text resize must remain functional — disabling viewport zoom is a WCAG failure",
      "Form elements must be large enough and spaced sufficiently to prevent adjacent-tap errors on mobile",
    ],
    methodology_summary: "Expert mapping of WCAG criteria to mobile contexts combined with user research involving mobile screen reader users and people with motor impairments using touchscreen devices.",
    sample_size: "Task force expert analysis supplemented by user research sessions with mobile assistive technology users",
    limitations: ["Published in 2015 — mobile platforms have evolved significantly", "Does not cover newer interaction patterns (e.g., swipe gestures, biometric authentication)", "Platform-specific guidance (iOS vs Android) is limited"],
    tags: ["mobile-accessibility", "wcag", "touch-targets", "gestures", "w3c", "wai", "screen-readers"],
    scores: [
      { criterion_name: "Qualitative and quantitative combination clearly defined", score: 7 },
      { criterion_name: "Whether methods corroborate each other", score: 7 },
      { criterion_name: "Sample sizes meet thresholds for both components", score: 6 },
      { criterion_name: "Integration methodology explained", score: 7 },
      { criterion_name: "Peer review status", score: 8 },
      { criterion_name: "Author credentials", score: 10 },
      { criterion_name: "Limitations of each method disclosed", score: 7 },
      { criterion_name: "Publication date", score: 5 },
      { criterion_name: "Citation count", score: 8 },
    ],
  },

  // ── More NNGroup Empirical Studies ─────────────────────────────────────
  {
    title: "Tabs, Used Right: Design Patterns for Tabbed Navigation",
    source_url: "https://www.nngroup.com/articles/tabs-used-right/",
    source_name: "NNGroup",
    authors: ["Jakob Nielsen"],
    publication_date: "2016-11-13",
    research_type: "user_testing",
    site_contexts: ["navigation_ia", "saas", "content_publishing"],
    attributed_summary: "Usability research on tabbed navigation patterns, identifying when tabs work well and common implementation mistakes that confuse users. Tabs are effective for switching between related content views within a single page context but fail when used for sequential steps or when they look like navigation buttons. The study emphasises that tab panels must appear directly below or adjacent to the tab bar to maintain a clear visual connection.",
    key_findings: [
      "Tabs work best for parallel content that users need to switch between — not for sequential workflows",
      "The active tab must be visually distinct with a clear connected-panel design (no gap between tab and content)",
      "Horizontal tabs should be limited to 5-7 items; beyond that, a different pattern is needed",
      "Users confuse tabs with navigation links when tabs look like buttons or are styled inconsistently",
      "Tab labels should be concise (1-2 words) and clearly differentiate the content in each panel",
      "Tabs that require scrolling to see all options (overflow tabs) cause 28% of users to miss content",
    ],
    methodology_summary: "Moderated usability testing across web applications and content sites, with task-based exercises measuring tab discovery, correct interpretation, and content-switching efficiency.",
    sample_size: "Multiple usability studies across web and SaaS applications",
    limitations: ["Desktop-focused — mobile tab patterns (e.g., segmented controls) behave differently", "Tab implementation varies significantly across component libraries"],
    tags: ["tabs", "tabbed-navigation", "content-switching", "nngroup", "ui-patterns", "component-design"],
    scores: [
      { criterion_name: "Sample size", score: 6 },
      { criterion_name: "Participant recruitment methodology", score: 6 },
      { criterion_name: "Demographic diversity and representation", score: 5 },
      { criterion_name: "Control variables documented", score: 7 },
      { criterion_name: "Variant / treatment clearly defined", score: 8 },
      { criterion_name: "Moderated vs unmoderated", score: 8 },
      { criterion_name: "Task success rate reported", score: 8 },
      { criterion_name: "Error rate documented", score: 6 },
      { criterion_name: "Time-on-task measured", score: 6 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 10 },
      { criterion_name: "Publication date (recency)", score: 6 },
      { criterion_name: "Limitations and bias disclosed", score: 6 },
      { criterion_name: "Replication or citation count", score: 7 },
    ],
  },
  {
    title: "Footers 101: Design Patterns and When Users Scroll Down",
    source_url: "https://www.nngroup.com/articles/footers/",
    source_name: "NNGroup",
    authors: ["Amy Schade"],
    publication_date: "2015-04-12",
    research_type: "user_testing",
    site_contexts: ["ecommerce_general", "content_publishing", "navigation_ia"],
    attributed_summary: "Usability research on website footer design, examining how users interact with footers and what content belongs there. The study found that users treat footers as a last resort for navigation — when main navigation fails, approximately 20% of users scroll to the footer for help. Effective footers serve as a secondary navigation hub containing contact information, legal links, and secondary category links that did not fit the main navigation.",
    key_findings: [
      "Approximately 20% of users scroll to the footer when they cannot find what they need in main navigation",
      "Fat footers with categorised links serve as a sitemap alternative and improve findability",
      "Contact information in the footer is expected by 64% of users as a trust signal",
      "Newsletter signup in the footer converts at 2-3x the rate of intrusive popup signups",
      "Footers should not duplicate the full primary navigation — they should offer complementary paths",
      "Social media links in the footer are clicked by fewer than 1% of visitors but are expected to be present",
    ],
    methodology_summary: "Usability testing with eye-tracking and click analytics examining footer usage patterns across e-commerce, content, and corporate websites.",
    sample_size: "Multiple usability studies and eye-tracking sessions",
    limitations: ["Footer interaction rates are low overall — sample sizes for footer-specific behaviour are small", "Mobile footer patterns differ significantly from desktop", "Infinite scroll disrupts traditional footer access"],
    tags: ["footers", "navigation", "secondary-navigation", "trust-signals", "nngroup", "page-structure"],
    scores: [
      { criterion_name: "Sample size", score: 6 },
      { criterion_name: "Participant recruitment methodology", score: 6 },
      { criterion_name: "Demographic diversity and representation", score: 5 },
      { criterion_name: "Control variables documented", score: 6 },
      { criterion_name: "Variant / treatment clearly defined", score: 7 },
      { criterion_name: "Moderated vs unmoderated", score: 8 },
      { criterion_name: "Task success rate reported", score: 7 },
      { criterion_name: "Error rate documented", score: 5 },
      { criterion_name: "Time-on-task measured", score: 5 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 9 },
      { criterion_name: "Publication date (recency)", score: 5 },
      { criterion_name: "Limitations and bias disclosed", score: 6 },
      { criterion_name: "Replication or citation count", score: 7 },
    ],
  },
];

async function seed() {
  console.log("UXMind Research Seeder — Batch 6\n");
  let inserted = 0, skipped = 0, rejected = 0;

  for (const entry of entries) {
    const result = calculateScore(entry.research_type, entry.scores);
    const slug = slugify(entry.title);
    console.log(`  [${result.passed ? "PASS" : "FAIL"}] ${result.breakdown.weighted_total.toFixed(1)}/100 — ${entry.title.slice(0, 65)}`);
    if (!result.passed) { rejected++; continue; }

    const { data: existing } = await supabase.from("research_entries").select("id").eq("slug", slug).limit(1);
    if (existing && existing.length > 0) { console.log(`    [skip] Already exists`); skipped++; continue; }

    const { error } = await supabase.from("research_entries").insert({
      title: entry.title, slug, attributed_summary: entry.attributed_summary,
      source_url: entry.source_url, source_name: entry.source_name,
      authors: entry.authors, publication_date: entry.publication_date,
      research_type: entry.research_type, site_contexts: entry.site_contexts,
      quality_score: result.breakdown.weighted_total, scoring_track: entry.research_type,
      scoring_breakdown: result.breakdown, key_findings: entry.key_findings,
      methodology_summary: entry.methodology_summary, sample_size: entry.sample_size,
      limitations: entry.limitations, tags: entry.tags, status: "published",
    });
    if (error) { console.error(`    [error] ${error.message}`); } else { inserted++; console.log(`    [inserted]`); }
  }
  console.log(`\nComplete: ${inserted} inserted, ${skipped} skipped, ${rejected} rejected`);
}
seed().catch((err) => { console.error("Fatal:", err); process.exit(1); });
