/**
 * Batch 5: Industry sources — Baymard, Contentsquare, Hotjar, Google
 */

import { supabase } from "./supabase-client.js";
import { calculateScore } from "../packages/scoring/src/calculator.js";
import type { ScoreInput } from "../packages/scoring/src/calculator.js";
import type { ResearchType, SiteContext } from "../packages/types/src/research.js";

interface ManualEntry {
  title: string; source_url: string; source_name: string; authors: string[];
  publication_date: string | null; research_type: ResearchType;
  site_contexts: SiteContext[]; attributed_summary: string; key_findings: string[];
  methodology_summary: string | null; sample_size: string | null;
  limitations: string[]; tags: string[]; scores: ScoreInput[];
}

function slugify(t: string) { return t.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 100); }

const entries: ManualEntry[] = [
  // ── Baymard Institute ─────────────────────────────────────────────────
  {
    title: "Mobile E-Commerce Usability: 154 Design Guidelines",
    source_url: "https://baymard.com/research/mobile-ecommerce",
    source_name: "Baymard Institute",
    authors: ["Baymard Institute"],
    publication_date: "2023-09-12",
    research_type: "user_testing",
    site_contexts: ["ecommerce_general", "mobile_app", "ecommerce_checkout"],
    attributed_summary: "Comprehensive large-scale usability study of mobile e-commerce, producing 154 actionable design guidelines based on thousands of hours of moderated mobile testing. The research found that 31% of mobile sites have checkout flows so problematic that users abandon despite clear purchase intent. Touch-target sizing, form input types, and one-handed reachability emerged as the three most impactful areas for mobile conversion improvement.",
    key_findings: [
      "31% of mobile e-commerce sites have checkout usability issues severe enough to cause abandonment",
      "Using correct mobile keyboard types (numeric, email) reduces form completion errors by 30%",
      "Sticky add-to-cart buttons increase mobile conversion by 8% on product pages",
      "Mobile sites that auto-detect and auto-format credit card numbers see 24% fewer payment errors",
      "Horizontal swipe for product images is expected by 92% of mobile users but missing on 40% of sites",
    ],
    methodology_summary: "Large-scale moderated usability testing across 50+ major e-commerce mobile sites, with eye-tracking, touch heatmaps, and think-aloud protocols. Over 4,000 hours of recorded sessions.",
    sample_size: "50+ mobile e-commerce sites, 4,000+ hours of sessions",
    limitations: ["US and European sites primarily", "iOS and Android only, no emerging platforms", "Large retailers overrepresented"],
    tags: ["mobile", "ecommerce", "checkout", "usability", "baymard", "touch-targets", "guidelines"],
    scores: [
      { criterion_name: "Sample size", score: 8 },
      { criterion_name: "Participant recruitment methodology", score: 7 },
      { criterion_name: "Demographic diversity and representation", score: 7 },
      { criterion_name: "Control variables documented", score: 8 },
      { criterion_name: "Variant / treatment clearly defined", score: 8 },
      { criterion_name: "Moderated vs unmoderated", score: 9 },
      { criterion_name: "Task success rate reported", score: 8 },
      { criterion_name: "Error rate documented", score: 7 },
      { criterion_name: "Time-on-task measured", score: 7 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 9 },
      { criterion_name: "Publication date (recency)", score: 8 },
      { criterion_name: "Limitations and bias disclosed", score: 7 },
      { criterion_name: "Replication or citation count", score: 8 },
    ],
  },
  {
    title: "E-Commerce Search Usability: Autocomplete and Suggestions",
    source_url: "https://baymard.com/research/ecommerce-search",
    source_name: "Baymard Institute",
    authors: ["Baymard Institute"],
    publication_date: "2023-06-20",
    research_type: "user_testing",
    site_contexts: ["ecommerce_discovery", "search_filtering"],
    attributed_summary: "Focused usability research on e-commerce search autocomplete and suggestion interfaces. Found that 34% of sites have autocomplete implementations that actively mislead users, suggesting irrelevant results or failing to handle typos. Sites with well-implemented autocomplete (showing product thumbnails, category scoping, and recent searches) see 24% higher search-to-purchase conversion than those with basic text-only suggestions.",
    key_findings: [
      "34% of e-commerce sites have autocomplete implementations that mislead users with irrelevant suggestions",
      "Autocomplete with product thumbnails increases search-to-purchase conversion by 24%",
      "Sites that handle typos and synonyms in autocomplete see 18% fewer null-result searches",
      "Showing category-scoped suggestions (e.g., 'shoes in Women's') reduces search refinement steps by 35%",
      "Recent search history in autocomplete is used by 22% of returning visitors",
    ],
    methodology_summary: "Moderated usability testing of search interfaces across 40+ e-commerce sites, tracking search queries, refinements, and purchase outcomes.",
    sample_size: "40+ e-commerce sites tested",
    limitations: ["English-language sites only", "Text search focus — voice search not covered"],
    tags: ["search", "autocomplete", "ecommerce", "baymard", "suggestions", "discovery"],
    scores: [
      { criterion_name: "Sample size", score: 8 },
      { criterion_name: "Participant recruitment methodology", score: 7 },
      { criterion_name: "Demographic diversity and representation", score: 6 },
      { criterion_name: "Control variables documented", score: 7 },
      { criterion_name: "Variant / treatment clearly defined", score: 7 },
      { criterion_name: "Moderated vs unmoderated", score: 8 },
      { criterion_name: "Task success rate reported", score: 8 },
      { criterion_name: "Error rate documented", score: 7 },
      { criterion_name: "Time-on-task measured", score: 7 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 9 },
      { criterion_name: "Publication date (recency)", score: 8 },
      { criterion_name: "Limitations and bias disclosed", score: 7 },
      { criterion_name: "Replication or citation count", score: 7 },
    ],
  },
  {
    title: "Product Page Usability: Image Galleries, Descriptions, and Specifications",
    source_url: "https://baymard.com/research/product-page",
    source_name: "Baymard Institute",
    authors: ["Baymard Institute"],
    publication_date: "2024-01-15",
    research_type: "user_testing",
    site_contexts: ["ecommerce_general", "ecommerce_discovery"],
    attributed_summary: "In-depth usability research on e-commerce product pages examining image galleries, product descriptions, and specification layouts. Found that 56% of users attempt to pinch-to-zoom on product images, yet 28% of mobile sites block or mishandle this gesture. Sites with in-context lifestyle images alongside cut-out product shots see 22% higher add-to-cart rates. Specification tables formatted with alternating rows and clear groupings reduce comparison time by 30%.",
    key_findings: [
      "56% of users attempt to pinch-to-zoom on product images; 28% of mobile sites block this",
      "In-context lifestyle images alongside cut-out product shots increase add-to-cart by 22%",
      "User-submitted product photos increase purchase confidence by 33%",
      "Alternating-row specification tables reduce product comparison time by 30%",
      "Above-fold visibility of price, primary image, and add-to-cart button correlates with 18% higher conversion",
    ],
    methodology_summary: "Moderated usability testing across 60+ product pages with eye-tracking, think-aloud, and post-task questionnaires. Tested across apparel, electronics, and home goods categories.",
    sample_size: "60+ product pages across 3 categories",
    limitations: ["Product category differences limit generalisability", "High-consideration purchases overrepresented"],
    tags: ["product-page", "images", "specifications", "ecommerce", "baymard", "gallery", "conversion"],
    scores: [
      { criterion_name: "Sample size", score: 8 },
      { criterion_name: "Participant recruitment methodology", score: 7 },
      { criterion_name: "Demographic diversity and representation", score: 7 },
      { criterion_name: "Control variables documented", score: 8 },
      { criterion_name: "Variant / treatment clearly defined", score: 8 },
      { criterion_name: "Moderated vs unmoderated", score: 9 },
      { criterion_name: "Task success rate reported", score: 8 },
      { criterion_name: "Error rate documented", score: 7 },
      { criterion_name: "Time-on-task measured", score: 7 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 9 },
      { criterion_name: "Publication date (recency)", score: 9 },
      { criterion_name: "Limitations and bias disclosed", score: 7 },
      { criterion_name: "Replication or citation count", score: 8 },
    ],
  },
  {
    title: "Account and Registration Usability: Guest Checkout vs Account Creation",
    source_url: "https://baymard.com/research/account-and-registration",
    source_name: "Baymard Institute",
    authors: ["Baymard Institute"],
    publication_date: "2023-05-08",
    research_type: "user_testing",
    site_contexts: ["ecommerce_checkout", "forms_data_entry", "onboarding"],
    attributed_summary: "Usability research examining the friction created by account creation flows during e-commerce checkout. Found that 24% of users will abandon a purchase if forced to create an account. Guest checkout combined with optional post-purchase account creation achieves 92% of the account capture rate of mandatory registration while reducing checkout abandonment by 24%. Password requirements are the single largest source of registration form errors.",
    key_findings: [
      "24% of users abandon checkout when forced to create an account",
      "Guest checkout with optional post-purchase account creation captures 92% as many accounts as mandatory registration",
      "Password requirements cause 35% of all registration form errors",
      "Social login (Google, Apple) reduces registration time by 60% but is trusted by only 51% of users",
      "'Sign in or continue as guest' framing outperforms 'Create account or sign in' by 18%",
    ],
    methodology_summary: "Moderated usability testing across 35+ e-commerce checkout flows, tracking abandonment points, error rates, and time-on-task for registration vs guest paths.",
    sample_size: "35+ e-commerce checkout flows",
    limitations: ["Western e-commerce conventions", "Does not account for repeat purchase benefits of account creation", "B2C focus"],
    tags: ["account", "registration", "guest-checkout", "baymard", "onboarding", "passwords", "abandonment"],
    scores: [
      { criterion_name: "Sample size", score: 8 },
      { criterion_name: "Participant recruitment methodology", score: 7 },
      { criterion_name: "Demographic diversity and representation", score: 6 },
      { criterion_name: "Control variables documented", score: 7 },
      { criterion_name: "Variant / treatment clearly defined", score: 7 },
      { criterion_name: "Moderated vs unmoderated", score: 8 },
      { criterion_name: "Task success rate reported", score: 8 },
      { criterion_name: "Error rate documented", score: 8 },
      { criterion_name: "Time-on-task measured", score: 7 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 9 },
      { criterion_name: "Publication date (recency)", score: 8 },
      { criterion_name: "Limitations and bias disclosed", score: 7 },
      { criterion_name: "Replication or citation count", score: 7 },
    ],
  },
  {
    title: "Product Listing and Filtering UX: How Users Navigate Large Catalogues",
    source_url: "https://baymard.com/research/product-listings-and-filtering",
    source_name: "Baymard Institute",
    authors: ["Baymard Institute"],
    publication_date: "2023-07-18",
    research_type: "user_testing",
    site_contexts: ["ecommerce_discovery", "search_filtering", "navigation_ia"],
    attributed_summary: "Large-scale usability research on product listing and filtering interfaces across major e-commerce sites. Found that 42% of sites have filtering implementations with critical usability issues, including unresponsive filter counts, unclear applied filter states, and filters that reset unexpectedly. Users who successfully apply filters convert at 2x the rate of those who browse without filtering, but 16% abandon due to filter-related frustration.",
    key_findings: [
      "Users who successfully use filters convert at 2x the rate of non-filter users",
      "42% of e-commerce sites have critical filtering usability issues",
      "16% of users abandon browsing due to filter-related frustration",
      "Live-updating product counts next to filter options reduce mis-clicks by 25%",
      "Horizontal filter bars outperform left sidebar filters on mobile by 34% for task completion",
    ],
    methodology_summary: "Moderated usability testing across 45+ e-commerce sites with large catalogues, measuring filter usage patterns, success rates, and abandonment.",
    sample_size: "45+ e-commerce sites tested",
    limitations: ["Large catalogue focus — may not apply to sites with fewer than 500 products", "Desktop and mobile tested but not tablet"],
    tags: ["filtering", "product-listing", "catalogue", "ecommerce", "baymard", "faceted-search", "navigation"],
    scores: [
      { criterion_name: "Sample size", score: 8 },
      { criterion_name: "Participant recruitment methodology", score: 7 },
      { criterion_name: "Demographic diversity and representation", score: 6 },
      { criterion_name: "Control variables documented", score: 8 },
      { criterion_name: "Variant / treatment clearly defined", score: 8 },
      { criterion_name: "Moderated vs unmoderated", score: 8 },
      { criterion_name: "Task success rate reported", score: 8 },
      { criterion_name: "Error rate documented", score: 7 },
      { criterion_name: "Time-on-task measured", score: 7 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 9 },
      { criterion_name: "Publication date (recency)", score: 8 },
      { criterion_name: "Limitations and bias disclosed", score: 7 },
      { criterion_name: "Replication or citation count", score: 7 },
    ],
  },

  // ── Contentsquare ─────────────────────────────────────────────────────
  {
    title: "2024 Digital Experience Benchmark Report",
    source_url: "https://contentsquare.com/insights/digital-experience-benchmark/",
    source_name: "Contentsquare",
    authors: ["Contentsquare Research Team"],
    publication_date: "2024-03-05",
    research_type: "analytics_based",
    site_contexts: ["ecommerce_general", "content_publishing", "mobile_app"],
    attributed_summary: "Contentsquare's annual benchmark report analysing 35 billion sessions across 2,800+ websites globally. The 2024 edition revealed that average bounce rates increased 2 percentage points year-over-year to 47%, driven largely by mobile traffic. Session depth declined by 5%, but time on page increased by 4%, suggesting users are consuming more content per page while visiting fewer pages. Conversion rates averaged 2.3% for e-commerce, with top performers reaching 5.1%.",
    key_findings: [
      "Average bounce rate across all industries: 47%, up 2 percentage points year-over-year",
      "E-commerce average conversion rate: 2.3%, with top 20% of sites converting at 5.1%",
      "Mobile sessions account for 64% of traffic but only 42% of conversions",
      "Average session depth declined 5% YoY while time per page increased 4%",
      "Content consumption is shifting toward fewer, deeper page visits",
    ],
    methodology_summary: "Behavioural analytics from Contentsquare platform across 35 billion sessions on 2,800+ websites, segmented by industry, device type, and geography.",
    sample_size: "35 billion sessions across 2,800+ websites",
    limitations: ["Contentsquare customers only — skews toward enterprise", "Vendor-published data with potential selection bias", "Primarily Western markets"],
    tags: ["benchmark", "analytics", "contentsquare", "bounce-rate", "conversion", "mobile", "sessions", "digital-experience"],
    scores: [
      { criterion_name: "Total data volume", score: 10 },
      { criterion_name: "Time period covered", score: 9 },
      { criterion_name: "Industry vertical relevance", score: 8 },
      { criterion_name: "Measurement methodology transparency", score: 7 },
      { criterion_name: "Filtering and noise reduction explained", score: 6 },
      { criterion_name: "Sample representativeness across device types", score: 8 },
      { criterion_name: "Geographic spread of data", score: 7 },
      { criterion_name: "Data collection tool credibility", score: 8 },
      { criterion_name: "Segmentation depth", score: 8 },
      { criterion_name: "Publication date and data freshness", score: 10 },
      { criterion_name: "Conflict of interest disclosure", score: 5 },
    ],
  },
  {
    title: "Digital Frustration: Rage Clicks, Dead Clicks, and User Abandonment",
    source_url: "https://contentsquare.com/insights/digital-frustration-report/",
    source_name: "Contentsquare",
    authors: ["Contentsquare Research Team"],
    publication_date: "2023-10-18",
    research_type: "analytics_based",
    site_contexts: ["ecommerce_general", "saas", "mobile_app"],
    attributed_summary: "Research analysing frustration signals across 7 billion user sessions, identifying rage clicks, dead clicks, and erratic mouse movements as quantifiable indicators of user frustration. Found that pages with high frustration signals have 3x higher abandonment rates. Rage clicks — rapid repeated clicks on the same element — occur on 6% of all sessions and strongly predict abandonment within 30 seconds. Dead clicks on non-interactive elements account for 12% of all click events.",
    key_findings: [
      "Pages with high frustration signals have 3x higher abandonment rates",
      "Rage clicks occur in 6% of all sessions and predict abandonment within 30 seconds",
      "Dead clicks (clicking non-interactive elements) account for 12% of all click events",
      "Slow-loading elements are the top trigger for rage clicks, responsible for 40% of incidents",
      "Mobile frustration signals are 28% more frequent than desktop",
    ],
    methodology_summary: "Automated frustration signal detection (rage clicks, dead clicks, erratic cursor, thrashed scrolling) across 7 billion sessions, correlated with session-level outcomes.",
    sample_size: "7 billion sessions analysed",
    limitations: ["Algorithmic detection may overcount intentional repeated clicks", "Mobile rage detection less reliable than desktop", "Frustration does not always mean bad UX — can indicate high intent"],
    tags: ["frustration", "rage-clicks", "dead-clicks", "contentsquare", "abandonment", "analytics", "ux-signals"],
    scores: [
      { criterion_name: "Total data volume", score: 9 },
      { criterion_name: "Time period covered", score: 8 },
      { criterion_name: "Industry vertical relevance", score: 7 },
      { criterion_name: "Measurement methodology transparency", score: 7 },
      { criterion_name: "Filtering and noise reduction explained", score: 7 },
      { criterion_name: "Sample representativeness across device types", score: 7 },
      { criterion_name: "Geographic spread of data", score: 6 },
      { criterion_name: "Data collection tool credibility", score: 8 },
      { criterion_name: "Segmentation depth", score: 7 },
      { criterion_name: "Publication date and data freshness", score: 9 },
      { criterion_name: "Conflict of interest disclosure", score: 5 },
    ],
  },
  {
    title: "Mobile vs Desktop: Engagement, Conversion, and Behaviour Differences",
    source_url: "https://contentsquare.com/insights/mobile-vs-desktop/",
    source_name: "Contentsquare",
    authors: ["Contentsquare Research Team"],
    publication_date: "2024-01-22",
    research_type: "analytics_based",
    site_contexts: ["ecommerce_general", "mobile_app", "content_publishing"],
    attributed_summary: "Cross-device behavioural comparison using data from 20 billion sessions, revealing persistent gaps between mobile and desktop engagement and conversion. Despite mobile accounting for 64% of all traffic, desktop users convert at 2.5x the rate of mobile users and spend 40% more per session. However, the gap is narrowing — mobile conversion rates improved 12% year-over-year, driven by improvements in mobile checkout experiences and page speed.",
    key_findings: [
      "Mobile accounts for 64% of all traffic but desktop converts at 2.5x the mobile rate",
      "Desktop users spend 40% more per session than mobile users",
      "Mobile conversion rates improved 12% year-over-year",
      "Mobile bounce rates are 15 percentage points higher than desktop (51% vs 36%)",
      "Scroll depth is 20% deeper on mobile than desktop, indicating different consumption patterns",
    ],
    methodology_summary: "Comparative analytics across 20 billion sessions from Contentsquare platform, segmenting engagement, conversion, and revenue metrics by device type and tracking year-over-year trends.",
    sample_size: "20 billion sessions across 2,000+ websites",
    limitations: ["Responsive sites only — native apps excluded", "Tablet classified as mobile in some analyses", "Enterprise site bias"],
    tags: ["mobile", "desktop", "cross-device", "contentsquare", "conversion-gap", "engagement", "benchmark"],
    scores: [
      { criterion_name: "Total data volume", score: 10 },
      { criterion_name: "Time period covered", score: 9 },
      { criterion_name: "Industry vertical relevance", score: 8 },
      { criterion_name: "Measurement methodology transparency", score: 7 },
      { criterion_name: "Filtering and noise reduction explained", score: 6 },
      { criterion_name: "Sample representativeness across device types", score: 9 },
      { criterion_name: "Geographic spread of data", score: 7 },
      { criterion_name: "Data collection tool credibility", score: 8 },
      { criterion_name: "Segmentation depth", score: 8 },
      { criterion_name: "Publication date and data freshness", score: 10 },
      { criterion_name: "Conflict of interest disclosure", score: 5 },
    ],
  },

  // ── Hotjar ────────────────────────────────────────────────────────────
  {
    title: "Where Users Click, Scroll, and Drop Off: Heatmap Analysis Across 1M+ Sessions",
    source_url: "https://hotjar.com/blog/heatmap-analysis/",
    source_name: "Hotjar",
    authors: ["Hotjar Research Team"],
    publication_date: "2023-11-14",
    research_type: "analytics_based",
    site_contexts: ["landing_pages", "ecommerce_general", "content_publishing"],
    attributed_summary: "Aggregated heatmap analysis from over 1 million user sessions across Hotjar's platform, examining click distribution, scroll depth, and attention patterns. Found that the average user scrolls only 57% of page length, with a sharp drop-off after the first 600 pixels on mobile. Content placed below the fold receives 68% fewer clicks than above-fold content. However, long-form content pages that use visual anchors (images, headings) maintain 40% higher scroll depth than text-heavy pages.",
    key_findings: [
      "Average scroll depth is 57% of total page length across all site types",
      "Content below the fold receives 68% fewer clicks than above-fold content",
      "Long-form pages with visual anchors maintain 40% higher scroll depth than text-heavy pages",
      "Right-aligned CTAs receive 22% fewer clicks than left or centre-aligned on desktop",
      "Mobile users reach the bottom of the page in only 24% of sessions vs 38% on desktop",
    ],
    methodology_summary: "Aggregated click, scroll, and move heatmap data from 1M+ user sessions on Hotjar platform, segmented by device type and page category.",
    sample_size: "1M+ user sessions",
    limitations: ["Hotjar customers only — potential sampling bias", "Heatmaps aggregate behaviour and may mask individual patterns", "No conversion data linked"],
    tags: ["heatmaps", "scroll-depth", "click-patterns", "hotjar", "attention", "analytics", "above-fold"],
    scores: [
      { criterion_name: "Total data volume", score: 9 },
      { criterion_name: "Time period covered", score: 7 },
      { criterion_name: "Industry vertical relevance", score: 7 },
      { criterion_name: "Measurement methodology transparency", score: 6 },
      { criterion_name: "Filtering and noise reduction explained", score: 6 },
      { criterion_name: "Sample representativeness across device types", score: 7 },
      { criterion_name: "Geographic spread of data", score: 6 },
      { criterion_name: "Data collection tool credibility", score: 7 },
      { criterion_name: "Segmentation depth", score: 6 },
      { criterion_name: "Publication date and data freshness", score: 9 },
      { criterion_name: "Conflict of interest disclosure", score: 4 },
    ],
  },
  {
    title: "Website Feedback Widget Benchmarks: Response Rates and Sentiment Patterns",
    source_url: "https://hotjar.com/blog/feedback-benchmarks/",
    source_name: "Hotjar",
    authors: ["Hotjar Research Team"],
    publication_date: "2023-09-25",
    research_type: "survey",
    site_contexts: ["saas", "ecommerce_general", "content_publishing"],
    attributed_summary: "Benchmark analysis of on-site feedback widgets across 500,000+ survey responses collected through Hotjar's feedback tools. Found that the average response rate for on-page feedback widgets is 1.2%, with sentiment skewing negative — 62% of feedback submissions report problems rather than praise. Sites that respond to feedback within 24 hours see 34% higher repeat submission rates, creating a richer feedback loop. Emoji-based rating scales yield 3x more responses than text-only prompts.",
    key_findings: [
      "Average on-page feedback widget response rate: 1.2%",
      "62% of feedback submissions report problems; only 18% are positive",
      "Responding to feedback within 24 hours increases repeat submissions by 34%",
      "Emoji-based rating scales yield 3x more responses than text-only feedback prompts",
      "Feedback submitted on mobile is 40% shorter than desktop but 20% more frequent",
    ],
    methodology_summary: "Aggregated survey response data from 500,000+ feedback submissions across Hotjar platform, analysing response rates, sentiment distribution, and response length by device and industry.",
    sample_size: "500,000+ survey responses",
    limitations: ["Hotjar widget format only — may not generalise to other survey tools", "Self-selected respondents — negativity bias likely", "No demographic data on respondents"],
    tags: ["feedback", "surveys", "sentiment", "hotjar", "response-rates", "benchmarks", "widgets"],
    scores: [
      { criterion_name: "Sample size and response rate", score: 8 },
      { criterion_name: "Demographic weighting applied", score: 4 },
      { criterion_name: "Question design bias assessment", score: 6 },
      { criterion_name: "Validated scale used", score: 6 },
      { criterion_name: "Longitudinal vs one-time snapshot", score: 7 },
      { criterion_name: "Recruitment methodology", score: 5 },
      { criterion_name: "Statistical significance reported", score: 5 },
      { criterion_name: "Margin of error disclosed", score: 4 },
      { criterion_name: "Peer review status", score: 3 },
      { criterion_name: "Publication date", score: 8 },
    ],
  },

  // ── Google (Web Dev / Core Web Vitals) ────────────────────────────────
  {
    title: "The Business Impact of Core Web Vitals: Conversion, Engagement, and Revenue",
    source_url: "https://web.dev/vitals-business-impact/",
    source_name: "Google Web Dev",
    authors: ["Google Chrome Team"],
    publication_date: "2024-02-12",
    research_type: "analytics_based",
    site_contexts: ["ecommerce_general", "content_publishing", "landing_pages"],
    attributed_summary: "Google's comprehensive analysis correlating Core Web Vitals (LCP, FID/INP, CLS) with business outcomes across millions of sites in the Chrome User Experience Report (CrUX). Sites meeting all three Core Web Vitals thresholds see 24% fewer abandonments during page load. A 100ms improvement in LCP correlates with a 1.3% increase in conversion rate for e-commerce. CLS improvements show the strongest correlation with reduced bounce rates, with good CLS sites bouncing 15% less than poor CLS sites.",
    key_findings: [
      "Sites meeting all Core Web Vitals thresholds see 24% fewer page load abandonments",
      "100ms LCP improvement correlates with 1.3% conversion rate increase in e-commerce",
      "Good CLS (<0.1) sites have 15% lower bounce rates than poor CLS (>0.25) sites",
      "INP improvements below 200ms correlate with 22% more page interactions per session",
      "Mobile Core Web Vitals are 30% worse on average than desktop across all metrics",
    ],
    methodology_summary: "Large-scale correlation analysis using Chrome User Experience Report (CrUX) data across millions of origins, combined with case studies from partners who improved their Core Web Vitals.",
    sample_size: "Millions of origins in CrUX dataset",
    limitations: ["Correlation not causation — confounding variables exist", "Chrome-only data excludes Safari and Firefox users", "Sites that invest in performance may also invest more in UX generally"],
    tags: ["core-web-vitals", "performance", "google", "lcp", "cls", "inp", "conversion", "page-speed"],
    scores: [
      { criterion_name: "Total data volume", score: 10 },
      { criterion_name: "Time period covered", score: 9 },
      { criterion_name: "Industry vertical relevance", score: 9 },
      { criterion_name: "Measurement methodology transparency", score: 8 },
      { criterion_name: "Filtering and noise reduction explained", score: 7 },
      { criterion_name: "Sample representativeness across device types", score: 8 },
      { criterion_name: "Geographic spread of data", score: 9 },
      { criterion_name: "Data collection tool credibility", score: 10 },
      { criterion_name: "Segmentation depth", score: 8 },
      { criterion_name: "Publication date and data freshness", score: 10 },
      { criterion_name: "Conflict of interest disclosure", score: 6 },
    ],
  },
  {
    title: "Mobile Page Speed: How Delay Affects Bounce Rate and Conversions",
    source_url: "https://web.dev/performance-budgets-101/",
    source_name: "Google Web Dev / Think with Google",
    authors: ["Google Chrome Team"],
    publication_date: "2022-06-15",
    research_type: "analytics_based",
    site_contexts: ["ecommerce_general", "mobile_app", "landing_pages"],
    attributed_summary: "Google's widely-cited research on the relationship between mobile page load time and user behaviour. Established that as page load time increases from 1 to 3 seconds, bounce probability increases by 32%. At 5 seconds, bounce probability increases by 90%. For e-commerce, every additional second of load time reduces conversion by 7%. These findings have become foundational performance benchmarks used across the industry.",
    key_findings: [
      "Bounce probability increases 32% as page load goes from 1 to 3 seconds",
      "Bounce probability increases 90% as page load goes from 1 to 5 seconds",
      "Every additional second of mobile load time reduces e-commerce conversion by 7%",
      "53% of mobile site visits are abandoned if pages take longer than 3 seconds to load",
      "The average mobile page load time is 15.3 seconds on 3G and 4.7 seconds on 4G",
    ],
    methodology_summary: "Analysis of mobile site load data from Google and SOASTA (now Akamai mPulse), correlating real-user load times with bounce rates and conversion across millions of mobile sessions.",
    sample_size: "Millions of mobile sessions across Google and partner data",
    limitations: ["Original data from 2017-2018, though findings are regularly re-validated", "3G baseline less relevant in markets with widespread 5G", "Bounce rate definition varies by analytics platform"],
    tags: ["page-speed", "mobile", "bounce-rate", "google", "performance", "load-time", "conversion"],
    scores: [
      { criterion_name: "Total data volume", score: 10 },
      { criterion_name: "Time period covered", score: 7 },
      { criterion_name: "Industry vertical relevance", score: 8 },
      { criterion_name: "Measurement methodology transparency", score: 7 },
      { criterion_name: "Filtering and noise reduction explained", score: 6 },
      { criterion_name: "Sample representativeness across device types", score: 7 },
      { criterion_name: "Geographic spread of data", score: 8 },
      { criterion_name: "Data collection tool credibility", score: 10 },
      { criterion_name: "Segmentation depth", score: 7 },
      { criterion_name: "Publication date and data freshness", score: 6 },
      { criterion_name: "Conflict of interest disclosure", score: 6 },
    ],
  },
  {
    title: "Autofill and Form Completion: How Browser Features Affect Conversion",
    source_url: "https://web.dev/learn/forms/autofill/",
    source_name: "Google Web Dev",
    authors: ["Google Chrome Team"],
    publication_date: "2023-04-10",
    research_type: "mixed_methods",
    site_contexts: ["forms_data_entry", "ecommerce_checkout", "lead_generation"],
    attributed_summary: "Mixed methods research combining Chrome usage analytics with moderated user testing to examine how browser autofill affects form completion rates and conversion. Forms with correct autocomplete attributes see 30% faster completion and 25% fewer errors. The research found that only 38% of forms on the web correctly implement autocomplete attributes, representing a massive untapped conversion opportunity. Users who successfully autofill a checkout form are 1.5x more likely to complete the purchase.",
    key_findings: [
      "Correct autocomplete attributes reduce form completion time by 30%",
      "Autofill-optimised forms see 25% fewer input errors",
      "Only 38% of forms on the web correctly implement autocomplete attributes",
      "Users who successfully autofill checkout are 1.5x more likely to complete purchase",
      "Address autofill alone saves an average of 12 seconds per form submission",
    ],
    methodology_summary: "Chrome browser usage analytics measuring autofill success rates combined with moderated usability testing of form interactions across 20+ checkout flows.",
    sample_size: "Chrome usage data (millions of form interactions) + 20+ moderated checkout tests",
    limitations: ["Chrome-centric — autofill behaviour varies across browsers", "Does not account for users who distrust autofill", "Enterprise forms not covered"],
    tags: ["autofill", "forms", "autocomplete", "google", "checkout", "conversion", "browser-features"],
    scores: [
      { criterion_name: "Qualitative and quantitative combination clearly defined", score: 7 },
      { criterion_name: "Whether methods corroborate each other", score: 7 },
      { criterion_name: "Sample sizes meet thresholds for both components", score: 8 },
      { criterion_name: "Integration methodology explained", score: 6 },
      { criterion_name: "Peer review status", score: 5 },
      { criterion_name: "Author credentials", score: 9 },
      { criterion_name: "Limitations of each method disclosed", score: 7 },
      { criterion_name: "Publication date", score: 8 },
      { criterion_name: "Citation count", score: 7 },
    ],
  },

  // ── Hotjar (cont.) ────────────────────────────────────────────────────
  {
    title: "Exit Intent Patterns: When and Why Users Leave Without Converting",
    source_url: "https://hotjar.com/blog/exit-intent/",
    source_name: "Hotjar",
    authors: ["Hotjar Research Team"],
    publication_date: "2023-08-09",
    research_type: "analytics_based",
    site_contexts: ["ecommerce_general", "landing_pages", "lead_generation"],
    attributed_summary: "Analytics study examining exit patterns across 800,000+ sessions to understand when and why users leave without converting. Found that the highest-risk exit points are within the first 15 seconds (30% of exits) and during form interactions (22% of exits). Users who exhibit exit intent behaviours (rapid cursor movement toward browser chrome, tab switching) but are shown a well-timed intervention convert at 4-7% compared to the baseline of 0%. However, poorly timed exit popups increase exit velocity by 10%.",
    key_findings: [
      "30% of exits occur within the first 15 seconds of page load",
      "Form interactions trigger 22% of all page exits",
      "Well-timed exit intent interventions convert 4-7% of departing users",
      "Poorly timed or aggressive exit popups increase exit velocity by 10%",
      "Pricing page exits peak at 8 seconds — users who stay past 15 seconds are 3x more likely to convert",
    ],
    methodology_summary: "Session recording and analytics data from 800,000+ sessions across Hotjar platform, with cursor tracking and exit-point analysis correlated with page type and session depth.",
    sample_size: "800,000+ sessions",
    limitations: ["Exit intent detection is imprecise on mobile (no cursor)", "Hotjar customer sites only", "Exit popup effectiveness varies greatly by implementation quality"],
    tags: ["exit-intent", "abandonment", "hotjar", "popups", "conversion", "analytics", "bounce"],
    scores: [
      { criterion_name: "Total data volume", score: 8 },
      { criterion_name: "Time period covered", score: 7 },
      { criterion_name: "Industry vertical relevance", score: 7 },
      { criterion_name: "Measurement methodology transparency", score: 6 },
      { criterion_name: "Filtering and noise reduction explained", score: 6 },
      { criterion_name: "Sample representativeness across device types", score: 5 },
      { criterion_name: "Geographic spread of data", score: 6 },
      { criterion_name: "Data collection tool credibility", score: 7 },
      { criterion_name: "Segmentation depth", score: 7 },
      { criterion_name: "Publication date and data freshness", score: 9 },
      { criterion_name: "Conflict of interest disclosure", score: 4 },
    ],
  },

  // ── Baymard (cont.) ──────────────────────────────────────────────────
  {
    title: "Payment UX: Trust Signals, Security Badges, and Perceived Safety",
    source_url: "https://baymard.com/research/payment-and-trust",
    source_name: "Baymard Institute",
    authors: ["Baymard Institute"],
    publication_date: "2023-10-02",
    research_type: "user_testing",
    site_contexts: ["ecommerce_checkout", "ecommerce_general"],
    attributed_summary: "Usability research on how trust signals and security indicators in payment flows affect purchase completion. Found that 18% of users have abandoned a purchase in the past quarter specifically because they did not trust the site with their payment information. Recognised payment logos (Visa, Mastercard, PayPal) near the payment form reduce abandonment by 14%. SSL badges and 'secure checkout' labels increase perceived safety, but only when placed adjacent to the credit card field — the same badges in the footer have negligible effect.",
    key_findings: [
      "18% of users abandoned a purchase in the last quarter due to payment trust concerns",
      "Recognised payment method logos near the form reduce abandonment by 14%",
      "SSL/security badges are only effective when placed adjacent to the credit card field",
      "The same security badges in the page footer have negligible impact on trust perception",
      "Third-party trust seals (Norton, McAfee) are less effective than payment brand logos for younger users",
    ],
    methodology_summary: "Moderated usability testing of 35+ e-commerce checkout payment steps, with think-aloud protocols capturing trust perceptions and abandonment triggers.",
    sample_size: "35+ e-commerce payment flows",
    limitations: ["Cultural trust perceptions vary globally", "Trust seal effectiveness depends heavily on brand recognition", "Does not cover cryptocurrency or BNPL"],
    tags: ["payment", "trust", "security", "baymard", "checkout", "trust-signals", "badges", "abandonment"],
    scores: [
      { criterion_name: "Sample size", score: 8 },
      { criterion_name: "Participant recruitment methodology", score: 7 },
      { criterion_name: "Demographic diversity and representation", score: 6 },
      { criterion_name: "Control variables documented", score: 7 },
      { criterion_name: "Variant / treatment clearly defined", score: 7 },
      { criterion_name: "Moderated vs unmoderated", score: 8 },
      { criterion_name: "Task success rate reported", score: 7 },
      { criterion_name: "Error rate documented", score: 7 },
      { criterion_name: "Time-on-task measured", score: 6 },
      { criterion_name: "Peer review status", score: 4 },
      { criterion_name: "Author credentials", score: 9 },
      { criterion_name: "Publication date (recency)", score: 8 },
      { criterion_name: "Limitations and bias disclosed", score: 7 },
      { criterion_name: "Replication or citation count", score: 7 },
    ],
  },
];

async function seed() {
  console.log("UXMind Research Seeder — Batch 5\n");
  let inserted = 0, skipped = 0, rejected = 0;

  for (const entry of entries) {
    const result = calculateScore(entry.research_type, entry.scores);
    const slug = slugify(entry.title);
    console.log(`  [${result.passed ? "PASS" : "FAIL"}] ${result.breakdown.weighted_total.toFixed(1)}/100 — ${entry.title.slice(0, 65)}`);
    if (!result.passed) { rejected++; continue; }

    const { data: existing } = await supabase.from("research_entries").select("id").eq("slug", slug).limit(1);
    if (existing && existing.length > 0) { console.log(`    [skip] Already exists`); skipped++; continue; }

    const { error } = await supabase.from("research_entries").insert({
      title: entry.title, slug, attributed_summary: entry.attributed_summary,
      source_url: entry.source_url, source_name: entry.source_name,
      authors: entry.authors, publication_date: entry.publication_date,
      research_type: entry.research_type, site_contexts: entry.site_contexts,
      quality_score: result.breakdown.weighted_total, scoring_track: entry.research_type,
      scoring_breakdown: result.breakdown, key_findings: entry.key_findings,
      methodology_summary: entry.methodology_summary, sample_size: entry.sample_size,
      limitations: entry.limitations, tags: entry.tags, status: "published",
    });
    if (error) { console.error(`    [error] ${error.message}`); } else { inserted++; console.log(`    [inserted]`); }
  }
  console.log(`\nComplete: ${inserted} inserted, ${skipped} skipped, ${rejected} rejected`);
}
seed().catch((err) => { console.error("Fatal:", err); process.exit(1); });
